/**
 * Combat-achievement reference data — OSRS Wiki `combat_achievement` bucket,
 * the SAME table the plugin's WikiCaRepository loads. `caTaskId` is the
 * in-game task id: the bit index (0–639) into the CA_TASK_COMPLETED
 * varplayers that the recipient's CombatAchievementTracker reads.
 *
 * GENERATED — do not hand-edit. Regenerate with `npm run gen:cas` (fetches the
 * wiki bucket API; see scripts/gen-cas.mjs).
 * Source: 637 tasks (Easy 41, Hard 85, Elite 162, Master 168, Grandmaster 121, Medium 60).
 */

export interface CaRef {
  /** In-game CA task id — the value `caTaskId` must carry on the wire (bit 0–639). */
  caTaskId: number;
  /** Task display name (e.g. "A Slow Death"). */
  name: string;
  /** Tier: Easy | Medium | Hard | Elite | Master | Grandmaster. */
  tier: string;
  /** Monster/encounter the task belongs to, when the wiki records one. */
  monster: string | null;
  /** Task category (Kill Count, Mechanical, Perfection, …). */
  type: string | null;
}

export const CAS: readonly CaRef[] = [
  { caTaskId: 0, name: "Noxious Foe", tier: "Easy", monster: "Aberrant Spectre", type: "Kill Count" },
  { caTaskId: 1, name: "Abyssal Adept", tier: "Hard", monster: "Abyssal Sire", type: "Kill Count" },
  { caTaskId: 2, name: "Abyssal Veteran", tier: "Elite", monster: "Abyssal Sire", type: "Kill Count" },
  { caTaskId: 3, name: "They Grow Up Too Fast", tier: "Hard", monster: "Abyssal Sire", type: "Mechanical" },
  { caTaskId: 4, name: "Respiratory Runner", tier: "Elite", monster: "Abyssal Sire", type: "Mechanical" },
  { caTaskId: 5, name: "Don't Whip Me", tier: "Hard", monster: "Abyssal Sire", type: "Mechanical" },
  { caTaskId: 6, name: "Demonic Rebound", tier: "Elite", monster: "Abyssal Sire", type: "Mechanical" },
  { caTaskId: 7, name: "Don't Stop Moving", tier: "Hard", monster: "Abyssal Sire", type: "Perfection" },
  { caTaskId: 8, name: "Perfect Sire", tier: "Elite", monster: "Abyssal Sire", type: "Perfection" },
  { caTaskId: 9, name: "Kree'arra Adept", tier: "Hard", monster: "Kree'arra", type: "Kill Count" },
  { caTaskId: 10, name: "Kree'arra Veteran", tier: "Elite", monster: "Kree'arra", type: "Kill Count" },
  { caTaskId: 11, name: "Collateral Damage", tier: "Master", monster: "Kree'arra", type: "Mechanical" },
  { caTaskId: 12, name: "Airborne Showdown", tier: "Hard", monster: "Kree'arra", type: "Mechanical" },
  { caTaskId: 13, name: "Swoop No More", tier: "Master", monster: "Kree'arra", type: "Perfection" },
  { caTaskId: 14, name: "The Worst Ranged Weapon", tier: "Grandmaster", monster: "Kree'arra", type: "Restriction" },
  { caTaskId: 15, name: "Feather Hunter", tier: "Grandmaster", monster: "Kree'arra", type: "Stamina" },
  { caTaskId: 16, name: "General Graardor Adept", tier: "Hard", monster: "General Graardor", type: "Kill Count" },
  { caTaskId: 17, name: "General Graardor Veteran", tier: "Elite", monster: "General Graardor", type: "Kill Count" },
  { caTaskId: 18, name: "Ourg Freezer", tier: "Hard", monster: "General Graardor", type: "Mechanical" },
  { caTaskId: 19, name: "Ourg Freezer II", tier: "Elite", monster: "General Graardor", type: "Mechanical" },
  { caTaskId: 20, name: "General Showdown", tier: "Hard", monster: "General Graardor", type: "Mechanical" },
  { caTaskId: 21, name: "Defence Matters", tier: "Grandmaster", monster: "General Graardor", type: "Perfection" },
  { caTaskId: 22, name: "Keep Away", tier: "Grandmaster", monster: "General Graardor", type: "Perfection" },
  { caTaskId: 23, name: "Ourg Killer", tier: "Grandmaster", monster: "General Graardor", type: "Stamina" },
  { caTaskId: 24, name: "Barrows Novice", tier: "Easy", monster: "Barrows", type: "Kill Count" },
  { caTaskId: 25, name: "Barrows Champion", tier: "Medium", monster: "Barrows", type: "Kill Count" },
  { caTaskId: 26, name: "Can't Touch Me", tier: "Medium", monster: "Barrows", type: "Mechanical" },
  { caTaskId: 27, name: "Pray for Success", tier: "Medium", monster: "Barrows", type: "Perfection" },
  { caTaskId: 28, name: "Defence? What Defence?", tier: "Easy", monster: "Barrows", type: "Restriction" },
  { caTaskId: 29, name: "Just Like That", tier: "Hard", monster: "Barrows", type: "Restriction" },
  { caTaskId: 30, name: "Faithless Crypt Run", tier: "Hard", monster: "Barrows", type: "Restriction" },
  { caTaskId: 31, name: "Reflecting on This Encounter", tier: "Elite", monster: "Basilisk Knight", type: "Kill Count" },
  { caTaskId: 32, name: "Big, Black and Fiery", tier: "Easy", monster: "Black Dragon", type: "Kill Count" },
  { caTaskId: 33, name: "The Demonic Punching Bag", tier: "Easy", monster: "Bloodveld", type: "Kill Count" },
  { caTaskId: 34, name: "Brutal, Big, Black and Firey", tier: "Medium", monster: "Brutal Black Dragon", type: "Kill Count" },
  { caTaskId: 35, name: "Bryophyta Novice", tier: "Easy", monster: "Bryophyta", type: "Kill Count" },
  { caTaskId: 36, name: "Bryophyta Champion", tier: "Medium", monster: "Bryophyta", type: "Kill Count" },
  { caTaskId: 37, name: "Protection from Moss", tier: "Easy", monster: "Bryophyta", type: "Mechanical" },
  { caTaskId: 38, name: "Quick Cutter", tier: "Medium", monster: "Bryophyta", type: "Mechanical" },
  { caTaskId: 39, name: "Preparation Is Key", tier: "Easy", monster: "Bryophyta", type: "Perfection" },
  { caTaskId: 40, name: "A Slow Death", tier: "Easy", monster: "Bryophyta", type: "Restriction" },
  { caTaskId: 41, name: "Fighting as Intended II", tier: "Easy", monster: "Bryophyta", type: "Restriction" },
  { caTaskId: 42, name: "Callisto Adept", tier: "Hard", monster: "Callisto", type: "Kill Count" },
  { caTaskId: 43, name: "Callisto Veteran", tier: "Elite", monster: "Callisto", type: "Kill Count" },
  { caTaskId: 44, name: "Skotizo Champion", tier: "Medium", monster: "Skotizo", type: "Kill Count" },
  { caTaskId: 45, name: "Skotizo Adept", tier: "Hard", monster: "Skotizo", type: "Kill Count" },
  { caTaskId: 46, name: "Demonic Weakening", tier: "Medium", monster: "Skotizo", type: "Mechanical" },
  { caTaskId: 47, name: "Demon Evasion", tier: "Elite", monster: "Skotizo", type: "Perfection" },
  { caTaskId: 48, name: "Demonbane Weaponry", tier: "Medium", monster: "Skotizo", type: "Restriction" },
  { caTaskId: 49, name: "Up for the Challenge", tier: "Elite", monster: "Skotizo", type: "Restriction" },
  { caTaskId: 50, name: "Precise Positioning", tier: "Master", monster: "Skotizo", type: "Restriction" },
  { caTaskId: 51, name: "Cerberus Veteran", tier: "Elite", monster: "Cerberus", type: "Kill Count" },
  { caTaskId: 52, name: "Cerberus Master", tier: "Master", monster: "Cerberus", type: "Kill Count" },
  { caTaskId: 53, name: "Arooo No More", tier: "Master", monster: "Cerberus", type: "Mechanical" },
  { caTaskId: 54, name: "Ghost Buster", tier: "Elite", monster: "Cerberus", type: "Mechanical" },
  { caTaskId: 55, name: "Unrequired Antifire", tier: "Elite", monster: "Cerberus", type: "Perfection" },
  { caTaskId: 56, name: "Anti-Bite Mechanics", tier: "Elite", monster: "Cerberus", type: "Perfection" },
  { caTaskId: 57, name: "Chaos Elemental Adept", tier: "Hard", monster: "Chaos Elemental", type: "Kill Count" },
  { caTaskId: 58, name: "Chaos Elemental Veteran", tier: "Elite", monster: "Chaos Elemental", type: "Kill Count" },
  { caTaskId: 59, name: "Hoarder", tier: "Hard", monster: "Chaos Elemental", type: "Mechanical" },
  { caTaskId: 60, name: "The Flincher", tier: "Hard", monster: "Chaos Elemental", type: "Perfection" },
  { caTaskId: 61, name: "Chaos Fanatic Champion", tier: "Medium", monster: "Chaos Fanatic", type: "Kill Count" },
  { caTaskId: 62, name: "Chaos Fanatic Adept", tier: "Hard", monster: "Chaos Fanatic", type: "Kill Count" },
  { caTaskId: 63, name: "Sorry, What Was That?", tier: "Medium", monster: "Chaos Fanatic", type: "Perfection" },
  { caTaskId: 64, name: "Praying to the Gods", tier: "Hard", monster: "Chaos Fanatic", type: "Restriction" },
  { caTaskId: 65, name: "Corporeal Beast Veteran", tier: "Elite", monster: "Corporeal Beast", type: "Kill Count" },
  { caTaskId: 66, name: "Corporeal Beast Master", tier: "Master", monster: "Corporeal Beast", type: "Kill Count" },
  { caTaskId: 67, name: "Hot on Your Feet", tier: "Elite", monster: "Corporeal Beast", type: "Perfection" },
  { caTaskId: 68, name: "Finding the Weak Spot", tier: "Elite", monster: "Corporeal Beast", type: "Restriction" },
  { caTaskId: 69, name: "Chicken Killer", tier: "Elite", monster: "Corporeal Beast", type: "Restriction" },
  { caTaskId: 70, name: "Crazy Archaeologist Champion", tier: "Medium", monster: "Crazy Archaeologist", type: "Kill Count" },
  { caTaskId: 71, name: "Crazy Archaeologist Adept", tier: "Hard", monster: "Crazy Archaeologist", type: "Kill Count" },
  { caTaskId: 72, name: "Mage of the Ruins", tier: "Medium", monster: "Crazy Archaeologist", type: "Mechanical" },
  { caTaskId: 73, name: "I'd Rather Not Learn", tier: "Medium", monster: "Crazy Archaeologist", type: "Perfection" },
  { caTaskId: 74, name: "If Gorillas Could Fly", tier: "Elite", monster: "Demonic Gorilla", type: "Kill Count" },
  { caTaskId: 75, name: "Hitting Them Where It Hurts", tier: "Elite", monster: "Demonic Gorilla", type: "Restriction" },
  { caTaskId: 76, name: "Deranged Archaeologist Novice", tier: "Easy", monster: "Deranged Archaeologist", type: "Kill Count" },
  { caTaskId: 77, name: "Deranged Archaeologist Champion", tier: "Medium", monster: "Deranged Archaeologist", type: "Kill Count" },
  { caTaskId: 78, name: "Mage of the Swamp", tier: "Medium", monster: "Deranged Archaeologist", type: "Mechanical" },
  { caTaskId: 79, name: "I'd Rather Be Illiterate", tier: "Medium", monster: "Deranged Archaeologist", type: "Perfection" },
  { caTaskId: 80, name: "The Walking Volcano", tier: "Easy", monster: "Fire Giant", type: "Kill Count" },
  { caTaskId: 81, name: "Galvek Speed-Trialist", tier: "Elite", monster: "Galvek", type: "Speed" },
  { caTaskId: 82, name: "Grotesque Guardians Adept", tier: "Hard", monster: "Grotesque Guardians", type: "Kill Count" },
  { caTaskId: 83, name: "Grotesque Guardians Veteran", tier: "Elite", monster: "Grotesque Guardians", type: "Kill Count" },
  { caTaskId: 84, name: "Don't Look at the Eclipse", tier: "Hard", monster: "Grotesque Guardians", type: "Mechanical" },
  { caTaskId: 85, name: "Prison Break", tier: "Hard", monster: "Grotesque Guardians", type: "Mechanical" },
  { caTaskId: 86, name: "Granite Footwork", tier: "Hard", monster: "Grotesque Guardians", type: "Mechanical" },
  { caTaskId: 87, name: "Heal No More", tier: "Hard", monster: "Grotesque Guardians", type: "Mechanical" },
  { caTaskId: 88, name: "Static Awareness", tier: "Hard", monster: "Grotesque Guardians", type: "Mechanical" },
  { caTaskId: 89, name: "Done before Dusk", tier: "Elite", monster: "Grotesque Guardians", type: "Mechanical" },
  { caTaskId: 90, name: "Perfect Grotesque Guardians", tier: "Elite", monster: "Grotesque Guardians", type: "Perfection" },
  { caTaskId: 91, name: "Perfect Grotesque Guardians II", tier: "Master", monster: "Grotesque Guardians", type: "Perfection" },
  { caTaskId: 92, name: "Grotesque Guardians Speed-Trialist", tier: "Elite", monster: "Grotesque Guardians", type: "Speed" },
  { caTaskId: 93, name: "Grotesque Guardians Speed-Chaser", tier: "Master", monster: "Grotesque Guardians", type: "Speed" },
  { caTaskId: 94, name: "Grotesque Guardians Speed-Runner", tier: "Grandmaster", monster: "Grotesque Guardians", type: "Speed" },
  { caTaskId: 95, name: "From Dusk...", tier: "Elite", monster: "Grotesque Guardians", type: "Stamina" },
  { caTaskId: 96, name: "... 'til Dawn", tier: "Master", monster: "Grotesque Guardians", type: "Stamina" },
  { caTaskId: 97, name: "A Smashing Time", tier: "Medium", monster: "Gargoyle", type: "Kill Count" },
  { caTaskId: 98, name: "Corrupted Gauntlet Veteran", tier: "Elite", monster: "Corrupted Hunllef", type: "Kill Count" },
  { caTaskId: 99, name: "Corrupted Gauntlet Master", tier: "Master", monster: "Corrupted Hunllef", type: "Kill Count" },
  { caTaskId: 100, name: "Corrupted Gauntlet Grandmaster", tier: "Grandmaster", monster: "Corrupted Hunllef", type: "Kill Count" },
  { caTaskId: 101, name: "3, 2, 1 - Mage", tier: "Elite", monster: "Corrupted Hunllef", type: "Perfection" },
  { caTaskId: 102, name: "Perfect Corrupted Hunllef", tier: "Master", monster: "Corrupted Hunllef", type: "Perfection" },
  { caTaskId: 103, name: "Defence Doesn't Matter II", tier: "Master", monster: "Corrupted Hunllef", type: "Restriction" },
  { caTaskId: 104, name: "Egniol Diet II", tier: "Grandmaster", monster: "Corrupted Hunllef", type: "Restriction" },
  { caTaskId: 105, name: "Corrupted Warrior", tier: "Master", monster: "Corrupted Hunllef", type: "Restriction" },
  { caTaskId: 106, name: "Wolf Puncher II", tier: "Grandmaster", monster: "Corrupted Hunllef", type: "Restriction" },
  { caTaskId: 107, name: "Corrupted Gauntlet Speed-Chaser", tier: "Master", monster: "Corrupted Hunllef", type: "Speed" },
  { caTaskId: 108, name: "Corrupted Gauntlet Speed-Runner", tier: "Grandmaster", monster: "Corrupted Hunllef", type: "Speed" },
  { caTaskId: 109, name: "Gauntlet Veteran", tier: "Elite", monster: "Crystalline Hunllef", type: "Kill Count" },
  { caTaskId: 110, name: "Gauntlet Master", tier: "Master", monster: "Crystalline Hunllef", type: "Kill Count" },
  { caTaskId: 111, name: "3, 2, 1 - Range", tier: "Elite", monster: "Crystalline Hunllef", type: "Perfection" },
  { caTaskId: 112, name: "Perfect Crystalline Hunllef", tier: "Master", monster: "Crystalline Hunllef", type: "Perfection" },
  { caTaskId: 113, name: "Defence Doesn't Matter", tier: "Master", monster: "Crystalline Hunllef", type: "Restriction" },
  { caTaskId: 114, name: "Egniol Diet", tier: "Elite", monster: "Crystalline Hunllef", type: "Restriction" },
  { caTaskId: 115, name: "Crystalline Warrior", tier: "Elite", monster: "Crystalline Hunllef", type: "Restriction" },
  { caTaskId: 116, name: "Wolf Puncher", tier: "Elite", monster: "Crystalline Hunllef", type: "Restriction" },
  { caTaskId: 117, name: "Gauntlet Speed-Chaser", tier: "Master", monster: "Crystalline Hunllef", type: "Speed" },
  { caTaskId: 118, name: "Gauntlet Speed-Runner", tier: "Grandmaster", monster: "Crystalline Hunllef", type: "Speed" },
  { caTaskId: 119, name: "Glough Speed-Trialist", tier: "Elite", monster: "Glough", type: "Speed" },
  { caTaskId: 120, name: "A Greater Foe", tier: "Easy", monster: "Greater Demon", type: "Kill Count" },
  { caTaskId: 121, name: "Not So Great After All", tier: "Easy", monster: "Greater Demon", type: "Restriction" },
  { caTaskId: 122, name: "A Demon's Best Friend", tier: "Easy", monster: "Hellhound", type: "Kill Count" },
  { caTaskId: 123, name: "Hespori Adept", tier: "Hard", monster: "Hespori", type: "Kill Count" },
  { caTaskId: 124, name: "Hesporisn't", tier: "Hard", monster: "Hespori", type: "Mechanical" },
  { caTaskId: 125, name: "Weed Whacker", tier: "Hard", monster: "Hespori", type: "Mechanical" },
  { caTaskId: 126, name: "Plant-Based Diet", tier: "Elite", monster: "Hespori", type: "Restriction" },
  { caTaskId: 127, name: "Hespori Speed-Trialist", tier: "Elite", monster: "Hespori", type: "Speed" },
  { caTaskId: 128, name: "Hespori Speed-Chaser", tier: "Master", monster: "Hespori", type: "Speed" },
  { caTaskId: 129, name: "Obor Novice", tier: "Easy", monster: "Obor", type: "Kill Count" },
  { caTaskId: 130, name: "Obor Champion", tier: "Medium", monster: "Obor", type: "Kill Count" },
  { caTaskId: 131, name: "Sleeping Giant", tier: "Easy", monster: "Obor", type: "Mechanical" },
  { caTaskId: 132, name: "Back to the Wall", tier: "Medium", monster: "Obor", type: "Mechanical" },
  { caTaskId: 133, name: "Squashing the Giant", tier: "Medium", monster: "Obor", type: "Perfection" },
  { caTaskId: 134, name: "Fighting as Intended", tier: "Easy", monster: "Obor", type: "Restriction" },
  { caTaskId: 135, name: "Alchemical Veteran", tier: "Elite", monster: "Alchemical Hydra", type: "Kill Count" },
  { caTaskId: 136, name: "Alchemical Master", tier: "Master", monster: "Alchemical Hydra", type: "Kill Count" },
  { caTaskId: 137, name: "Unrequired Antipoisons", tier: "Master", monster: "Alchemical Hydra", type: "Mechanical" },
  { caTaskId: 138, name: "Lightning Lure", tier: "Master", monster: "Alchemical Hydra", type: "Mechanical" },
  { caTaskId: 139, name: "Don't Flame Me", tier: "Master", monster: "Alchemical Hydra", type: "Mechanical" },
  { caTaskId: 140, name: "Mixing Correctly", tier: "Master", monster: "Alchemical Hydra", type: "Mechanical" },
  { caTaskId: 141, name: "The Flame Skipper", tier: "Master", monster: "Alchemical Hydra", type: "Mechanical" },
  { caTaskId: 142, name: "Alcleanical Hydra", tier: "Master", monster: "Alchemical Hydra", type: "Perfection" },
  { caTaskId: 143, name: "No Pressure", tier: "Grandmaster", monster: "Alchemical Hydra", type: "Restriction" },
  { caTaskId: 144, name: "Alchemical Speed-Chaser", tier: "Master", monster: "Alchemical Hydra", type: "Speed" },
  { caTaskId: 145, name: "Alchemical Speed-Runner", tier: "Grandmaster", monster: "Alchemical Hydra", type: "Speed" },
  { caTaskId: 146, name: "Working Overtime", tier: "Master", monster: "Alchemical Hydra", type: "Stamina" },
  { caTaskId: 147, name: "Fight Caves Veteran", tier: "Elite", monster: "TzTok-Jad", type: "Kill Count" },
  { caTaskId: 148, name: "Fight Caves Master", tier: "Master", monster: "TzTok-Jad", type: "Kill Count" },
  { caTaskId: 149, name: "A Near Miss!", tier: "Elite", monster: "TzTok-Jad", type: "Mechanical" },
  { caTaskId: 150, name: "Denying the Healers", tier: "Master", monster: "TzTok-Jad", type: "Mechanical" },
  { caTaskId: 151, name: "Denying the Healers II", tier: "Grandmaster", monster: "TzTok-Jad", type: "Mechanical" },
  { caTaskId: 152, name: "You Didn't Say Anything About a Bat", tier: "Master", monster: "TzTok-Jad", type: "Mechanical" },
  { caTaskId: 153, name: "Facing Jad Head-on", tier: "Elite", monster: "TzTok-Jad", type: "Restriction" },
  { caTaskId: 154, name: "No Time for a Drink", tier: "Grandmaster", monster: "TzTok-Jad", type: "Restriction" },
  { caTaskId: 155, name: "Fight Caves Speed-Chaser", tier: "Master", monster: "TzTok-Jad", type: "Speed" },
  { caTaskId: 156, name: "Fight Caves Speed-Runner", tier: "Grandmaster", monster: "TzTok-Jad", type: "Speed" },
  { caTaskId: 157, name: "Kalphite Queen Adept", tier: "Hard", monster: "Kalphite Queen", type: "Kill Count" },
  { caTaskId: 158, name: "Kalphite Queen Veteran", tier: "Elite", monster: "Kalphite Queen", type: "Kill Count" },
  { caTaskId: 159, name: "Chitin Penetrator", tier: "Hard", monster: "Kalphite Queen", type: "Mechanical" },
  { caTaskId: 160, name: "Insect Deflection", tier: "Elite", monster: "Kalphite Queen", type: "Mechanical" },
  { caTaskId: 161, name: "Prayer Smasher", tier: "Elite", monster: "Kalphite Queen", type: "Restriction" },
  { caTaskId: 162, name: "King Black Dragon Novice", tier: "Easy", monster: "King Black Dragon", type: "Kill Count" },
  { caTaskId: 163, name: "King Black Dragon Champion", tier: "Medium", monster: "King Black Dragon", type: "Kill Count" },
  { caTaskId: 164, name: "Claw Clipper", tier: "Medium", monster: "King Black Dragon", type: "Mechanical" },
  { caTaskId: 165, name: "Hide Penetration", tier: "Medium", monster: "King Black Dragon", type: "Restriction" },
  { caTaskId: 166, name: "Antifire Protection", tier: "Medium", monster: "King Black Dragon", type: "Restriction" },
  { caTaskId: 167, name: "Who Is the King Now?", tier: "Hard", monster: "King Black Dragon", type: "Stamina" },
  { caTaskId: 168, name: "Kraken Adept", tier: "Hard", monster: "Kraken", type: "Kill Count" },
  { caTaskId: 169, name: "Unnecessary Optimisation", tier: "Hard", monster: "Kraken", type: "Mechanical" },
  { caTaskId: 170, name: "Krakan't Hurt Me", tier: "Hard", monster: "Kraken", type: "Stamina" },
  { caTaskId: 171, name: "Ten-tacles", tier: "Elite", monster: "Kraken", type: "Stamina" },
  { caTaskId: 172, name: "One Hundred Tentacles", tier: "Master", monster: "Kraken", type: "Stamina" },
  { caTaskId: 173, name: "Master of Broad Weaponry", tier: "Medium", monster: "Kurask", type: "Kill Count" },
  { caTaskId: 174, name: "A Scaley Encounter", tier: "Easy", monster: "Lizardman Shaman", type: "Kill Count" },
  { caTaskId: 175, name: "Shayzien Protector", tier: "Easy", monster: "Lizardman Shaman", type: "Perfection" },
  { caTaskId: 176, name: "Mimic Veteran", tier: "Elite", monster: "The Mimic", type: "Kill Count" },
  { caTaskId: 177, name: "Giant Mole Novice", tier: "Easy", monster: "Giant Mole", type: "Kill Count" },
  { caTaskId: 178, name: "Giant Mole Champion", tier: "Medium", monster: "Giant Mole", type: "Kill Count" },
  { caTaskId: 179, name: "Why Are You Running?", tier: "Hard", monster: "Giant Mole", type: "Mechanical" },
  { caTaskId: 180, name: "Hard Hitter", tier: "Elite", monster: "Giant Mole", type: "Mechanical" },
  { caTaskId: 181, name: "Whack-a-Mole", tier: "Hard", monster: "Giant Mole", type: "Mechanical" },
  { caTaskId: 182, name: "Avoiding Those Little Arms", tier: "Medium", monster: "Giant Mole", type: "Perfection" },
  { caTaskId: 183, name: "Nightmare Adept", tier: "Hard", monster: "The Nightmare", type: "Kill Count" },
  { caTaskId: 184, name: "Nightmare Veteran", tier: "Elite", monster: "The Nightmare", type: "Kill Count" },
  { caTaskId: 185, name: "Nightmare Master", tier: "Master", monster: "The Nightmare", type: "Kill Count" },
  { caTaskId: 186, name: "Terrible Parent", tier: "Grandmaster", monster: "The Nightmare", type: "Mechanical" },
  { caTaskId: 187, name: "Explosion!", tier: "Elite", monster: "The Nightmare", type: "Mechanical" },
  { caTaskId: 188, name: "Perfect Nightmare", tier: "Master", monster: "The Nightmare", type: "Perfection" },
  { caTaskId: 189, name: "Sleep Tight", tier: "Elite", monster: "The Nightmare", type: "Restriction" },
  { caTaskId: 190, name: "A Long Trip", tier: "Grandmaster", monster: "The Nightmare", type: "Restriction" },
  { caTaskId: 191, name: "Nightmare (Solo) Speed-Trialist", tier: "Elite", monster: "The Nightmare", type: "Speed" },
  { caTaskId: 192, name: "Nightmare (Solo) Speed-Chaser", tier: "Master", monster: "The Nightmare", type: "Speed" },
  { caTaskId: 193, name: "Nightmare (Solo) Speed-Runner", tier: "Grandmaster", monster: "The Nightmare", type: "Speed" },
  { caTaskId: 194, name: "Nightmare (5-Scale) Speed-Trialist", tier: "Elite", monster: "The Nightmare", type: "Speed" },
  { caTaskId: 195, name: "Nightmare (5-Scale) Speed-Chaser", tier: "Master", monster: "The Nightmare", type: "Speed" },
  { caTaskId: 196, name: "Nightmare (5-Scale) Speed-Runner", tier: "Grandmaster", monster: "The Nightmare", type: "Speed" },
  { caTaskId: 197, name: "Dagannoth Prime Champion", tier: "Medium", monster: "Dagannoth Prime", type: "Kill Count" },
  { caTaskId: 198, name: "Dagannoth Prime Adept", tier: "Hard", monster: "Dagannoth Prime", type: "Kill Count" },
  { caTaskId: 199, name: "Death to the Seer King", tier: "Elite", monster: "Dagannoth Prime", type: "Mechanical" },
  { caTaskId: 200, name: "From One King to Another", tier: "Elite", monster: "Dagannoth Prime", type: "Mechanical" },
  { caTaskId: 201, name: "Dagannoth Rex Champion", tier: "Medium", monster: "Dagannoth Rex", type: "Kill Count" },
  { caTaskId: 202, name: "Dagannoth Rex Adept", tier: "Hard", monster: "Dagannoth Rex", type: "Kill Count" },
  { caTaskId: 203, name: "Death to the Warrior King", tier: "Elite", monster: "Dagannoth Rex", type: "Mechanical" },
  { caTaskId: 204, name: "A Frozen King", tier: "Medium", monster: "Dagannoth Rex", type: "Mechanical" },
  { caTaskId: 205, name: "Toppling the Diarchy", tier: "Elite", monster: "Dagannoth Rex", type: "Mechanical" },
  { caTaskId: 206, name: "Sarachnis Novice", tier: "Easy", monster: "Sarachnis", type: "Kill Count" },
  { caTaskId: 207, name: "Sarachnis Champion", tier: "Medium", monster: "Sarachnis", type: "Kill Count" },
  { caTaskId: 208, name: "Ready to Pounce", tier: "Hard", monster: "Sarachnis", type: "Mechanical" },
  { caTaskId: 209, name: "Inspect Repellent", tier: "Hard", monster: "Sarachnis", type: "Perfection" },
  { caTaskId: 210, name: "Newspaper Enthusiast", tier: "Medium", monster: "Sarachnis", type: "Restriction" },
  { caTaskId: 211, name: "Commander Zilyana Adept", tier: "Hard", monster: "Commander Zilyana", type: "Kill Count" },
  { caTaskId: 212, name: "Commander Zilyana Veteran", tier: "Elite", monster: "Commander Zilyana", type: "Kill Count" },
  { caTaskId: 213, name: "Commander Showdown", tier: "Hard", monster: "Commander Zilyana", type: "Mechanical" },
  { caTaskId: 214, name: "Animal Whisperer", tier: "Grandmaster", monster: "Commander Zilyana", type: "Perfection" },
  { caTaskId: 215, name: "Moving Collateral", tier: "Master", monster: "Commander Zilyana", type: "Restriction" },
  { caTaskId: 216, name: "Reminisce", tier: "Elite", monster: "Commander Zilyana", type: "Restriction" },
  { caTaskId: 217, name: "Peach Conjurer", tier: "Grandmaster", monster: "Commander Zilyana", type: "Stamina" },
  { caTaskId: 218, name: "Scorpia Adept", tier: "Hard", monster: "Scorpia", type: "Kill Count" },
  { caTaskId: 219, name: "Scorpia Veteran", tier: "Elite", monster: "Scorpia", type: "Kill Count" },
  { caTaskId: 220, name: "I Can't Reach That", tier: "Hard", monster: "Scorpia", type: "Perfection" },
  { caTaskId: 221, name: "Guardians No More", tier: "Hard", monster: "Scorpia", type: "Restriction" },
  { caTaskId: 222, name: "Fragment of Seren Speed-Trialist", tier: "Elite", monster: "Fragment of Seren", type: "Speed" },
  { caTaskId: 223, name: "A Frozen Foe from the Past", tier: "Medium", monster: "Skeletal Wyvern", type: "Kill Count" },
  { caTaskId: 224, name: "Zulrah Adept", tier: "Hard", monster: "Zulrah", type: "Kill Count" },
  { caTaskId: 225, name: "Zulrah Veteran", tier: "Elite", monster: "Zulrah", type: "Kill Count" },
  { caTaskId: 226, name: "Zulrah Master", tier: "Master", monster: "Zulrah", type: "Kill Count" },
  { caTaskId: 227, name: "Snake Rebound", tier: "Elite", monster: "Zulrah", type: "Mechanical" },
  { caTaskId: 228, name: "Snake. Snake!? Snaaaaaake!", tier: "Elite", monster: "Zulrah", type: "Mechanical" },
  { caTaskId: 229, name: "Perfect Zulrah", tier: "Master", monster: "Zulrah", type: "Perfection" },
  { caTaskId: 230, name: "Zulrah Speed-Trialist", tier: "Elite", monster: "Zulrah", type: "Speed" },
  { caTaskId: 231, name: "Zulrah Speed-Chaser", tier: "Master", monster: "Zulrah", type: "Speed" },
  { caTaskId: 232, name: "Zulrah Speed-Runner", tier: "Grandmaster", monster: "Zulrah", type: "Speed" },
  { caTaskId: 233, name: "Dagannoth Supreme Champion", tier: "Medium", monster: "Dagannoth Supreme", type: "Kill Count" },
  { caTaskId: 234, name: "Dagannoth Supreme Adept", tier: "Hard", monster: "Dagannoth Supreme", type: "Kill Count" },
  { caTaskId: 235, name: "Death to the Archer King", tier: "Elite", monster: "Dagannoth Supreme", type: "Mechanical" },
  { caTaskId: 236, name: "Rapid Succession", tier: "Elite", monster: "Dagannoth Supreme", type: "Mechanical" },
  { caTaskId: 237, name: "Theatre of Blood Veteran", tier: "Elite", monster: "Theatre of Blood", type: "Kill Count" },
  { caTaskId: 238, name: "Theatre of Blood Master", tier: "Master", monster: "Theatre of Blood", type: "Kill Count" },
  { caTaskId: 239, name: "Theatre of Blood Grandmaster", tier: "Grandmaster", monster: "Theatre of Blood", type: "Kill Count" },
  { caTaskId: 240, name: "Two-Down", tier: "Master", monster: "Theatre of Blood", type: "Mechanical" },
  { caTaskId: 241, name: "Pop It", tier: "Master", monster: "Theatre of Blood", type: "Mechanical" },
  { caTaskId: 242, name: "A Timely Snack", tier: "Master", monster: "Theatre of Blood", type: "Mechanical" },
  { caTaskId: 243, name: "Perfect Theatre", tier: "Grandmaster", monster: "Theatre of Blood", type: "Perfection" },
  { caTaskId: 244, name: "Perfect Maiden", tier: "Master", monster: "Theatre of Blood", type: "Perfection" },
  { caTaskId: 245, name: "Perfect Bloat", tier: "Master", monster: "Theatre of Blood", type: "Perfection" },
  { caTaskId: 246, name: "Perfect Nylocas", tier: "Master", monster: "Theatre of Blood", type: "Perfection" },
  { caTaskId: 247, name: "Perfect Sotetseg", tier: "Master", monster: "Theatre of Blood", type: "Perfection" },
  { caTaskId: 248, name: "Perfect Xarpus", tier: "Master", monster: "Theatre of Blood", type: "Perfection" },
  { caTaskId: 249, name: "Perfect Verzik", tier: "Master", monster: "Theatre of Blood", type: "Perfection" },
  { caTaskId: 250, name: "Can't Drain This", tier: "Master", monster: "Theatre of Blood", type: "Restriction" },
  { caTaskId: 251, name: "Can You Dance?", tier: "Master", monster: "Theatre of Blood", type: "Restriction" },
  { caTaskId: 252, name: "Morytania Only", tier: "Grandmaster", monster: "Theatre of Blood", type: "Restriction" },
  { caTaskId: 253, name: "Back in My Day...", tier: "Master", monster: "Theatre of Blood", type: "Restriction" },
  { caTaskId: 254, name: "Theatre (Duo) Speed-Runner", tier: "Grandmaster", monster: "Theatre of Blood", type: "Speed" },
  { caTaskId: 255, name: "Theatre (Trio) Speed-Chaser", tier: "Master", monster: "Theatre of Blood", type: "Speed" },
  { caTaskId: 256, name: "Theatre (Trio) Speed-Runner", tier: "Grandmaster", monster: "Theatre of Blood", type: "Speed" },
  { caTaskId: 257, name: "Theatre (4-Scale) Speed-Chaser", tier: "Master", monster: "Theatre of Blood", type: "Speed" },
  { caTaskId: 258, name: "Theatre (4-Scale) Speed-Runner", tier: "Grandmaster", monster: "Theatre of Blood", type: "Speed" },
  { caTaskId: 259, name: "Theatre (5-Scale) Speed-Chaser", tier: "Master", monster: "Theatre of Blood", type: "Speed" },
  { caTaskId: 260, name: "Theatre (5-Scale) Speed-Runner", tier: "Grandmaster", monster: "Theatre of Blood", type: "Speed" },
  { caTaskId: 261, name: "Thermonuclear Veteran", tier: "Elite", monster: "Thermonuclear Smoke Devil", type: "Kill Count" },
  { caTaskId: 262, name: "Hazard Prevention", tier: "Elite", monster: "Thermonuclear Smoke Devil", type: "Perfection" },
  { caTaskId: 263, name: "Spec'd Out", tier: "Elite", monster: "Thermonuclear Smoke Devil", type: "Restriction" },
  { caTaskId: 264, name: "Venenatis Adept", tier: "Hard", monster: "Venenatis", type: "Kill Count" },
  { caTaskId: 265, name: "Venenatis Veteran", tier: "Elite", monster: "Venenatis", type: "Kill Count" },
  { caTaskId: 266, name: "Vet'ion Adept", tier: "Hard", monster: "Vet'ion", type: "Kill Count" },
  { caTaskId: 267, name: "Vet'eran", tier: "Elite", monster: "Vet'ion", type: "Kill Count" },
  { caTaskId: 268, name: "Vorkath Veteran", tier: "Elite", monster: "Vorkath", type: "Kill Count" },
  { caTaskId: 269, name: "Vorkath Master", tier: "Master", monster: "Vorkath", type: "Kill Count" },
  { caTaskId: 270, name: "The Walk", tier: "Master", monster: "Vorkath", type: "Mechanical" },
  { caTaskId: 271, name: "Zombie Destroyer", tier: "Elite", monster: "Vorkath", type: "Restriction" },
  { caTaskId: 272, name: "Dodging the Dragon", tier: "Master", monster: "Vorkath", type: "Perfection" },
  { caTaskId: 273, name: "Stick 'em With the Pointy End", tier: "Elite", monster: "Vorkath", type: "Restriction" },
  { caTaskId: 274, name: "Faithless Encounter", tier: "Grandmaster", monster: "Vorkath", type: "Restriction" },
  { caTaskId: 275, name: "The Fremennik Way", tier: "Grandmaster", monster: "Vorkath", type: "Restriction" },
  { caTaskId: 276, name: "Vorkath Speed-Chaser", tier: "Master", monster: "Vorkath", type: "Speed" },
  { caTaskId: 277, name: "Vorkath Speed-Runner", tier: "Grandmaster", monster: "Vorkath", type: "Speed" },
  { caTaskId: 278, name: "Extended Encounter", tier: "Master", monster: "Vorkath", type: "Stamina" },
  { caTaskId: 279, name: "Wintertodt Novice", tier: "Easy", monster: "Wintertodt", type: "Kill Count" },
  { caTaskId: 280, name: "Wintertodt Champion", tier: "Medium", monster: "Wintertodt", type: "Kill Count" },
  { caTaskId: 281, name: "Mummy!", tier: "Easy", monster: "Wintertodt", type: "Mechanical" },
  { caTaskId: 282, name: "Handyman", tier: "Easy", monster: "Wintertodt", type: "Mechanical" },
  { caTaskId: 283, name: "Can We Fix It?", tier: "Medium", monster: "Wintertodt", type: "Perfection" },
  { caTaskId: 284, name: "Leaving No One Behind", tier: "Medium", monster: "Wintertodt", type: "Restriction" },
  { caTaskId: 285, name: "Cosy", tier: "Easy", monster: "Wintertodt", type: "Restriction" },
  { caTaskId: 286, name: "Why Fletch?", tier: "Hard", monster: "Wintertodt", type: "Stamina" },
  { caTaskId: 287, name: "A Slithery Encounter", tier: "Easy", monster: "Wyrm", type: "Kill Count" },
  { caTaskId: 288, name: "Chambers of Xeric: CM Master", tier: "Master", monster: "Chambers of Xeric: Challenge Mode", type: "Kill Count" },
  { caTaskId: 289, name: "Chambers of Xeric: CM Grandmaster", tier: "Grandmaster", monster: "Chambers of Xeric: Challenge Mode", type: "Kill Count" },
  { caTaskId: 290, name: "Immortal Raid Team", tier: "Master", monster: "Chambers of Xeric: Challenge Mode", type: "Perfection" },
  { caTaskId: 291, name: "Immortal Raider", tier: "Master", monster: "Chambers of Xeric: Challenge Mode", type: "Perfection" },
  { caTaskId: 292, name: "Dust Seeker", tier: "Elite", monster: "Chambers of Xeric: Challenge Mode", type: "Speed" },
  { caTaskId: 293, name: "Chambers of Xeric: CM (Solo) Speed-Chaser", tier: "Master", monster: "Chambers of Xeric: Challenge Mode", type: "Speed" },
  { caTaskId: 294, name: "Chambers of Xeric: CM (Solo) Speed-Runner", tier: "Grandmaster", monster: "Chambers of Xeric: Challenge Mode", type: "Speed" },
  { caTaskId: 295, name: "Chambers of Xeric: CM (5-Scale) Speed-Chaser", tier: "Master", monster: "Chambers of Xeric: Challenge Mode", type: "Speed" },
  { caTaskId: 296, name: "Chambers of Xeric: CM (5-Scale) Speed-Runner", tier: "Grandmaster", monster: "Chambers of Xeric: Challenge Mode", type: "Speed" },
  { caTaskId: 297, name: "Chambers of Xeric: CM (Trio) Speed-Chaser", tier: "Master", monster: "Chambers of Xeric: Challenge Mode", type: "Speed" },
  { caTaskId: 298, name: "Chambers of Xeric: CM (Trio) Speed-Runner", tier: "Grandmaster", monster: "Chambers of Xeric: Challenge Mode", type: "Speed" },
  { caTaskId: 299, name: "Chambers of Xeric Veteran", tier: "Elite", monster: "Chambers of Xeric", type: "Kill Count" },
  { caTaskId: 300, name: "Chambers of Xeric Master", tier: "Master", monster: "Chambers of Xeric", type: "Kill Count" },
  { caTaskId: 301, name: "Chambers of Xeric Grandmaster", tier: "Grandmaster", monster: "Chambers of Xeric", type: "Kill Count" },
  { caTaskId: 302, name: "Perfectly Balanced", tier: "Elite", monster: "Chambers of Xeric", type: "Mechanical" },
  { caTaskId: 303, name: "Together We'll Fall", tier: "Elite", monster: "Chambers of Xeric", type: "Mechanical" },
  { caTaskId: 304, name: "No Time for Death", tier: "Master", monster: "Chambers of Xeric", type: "Mechanical" },
  { caTaskId: 305, name: "Putting It Olm on the Line", tier: "Master", monster: "Chambers of Xeric", type: "Mechanical" },
  { caTaskId: 306, name: "A Not So Special Lizard", tier: "Master", monster: "Chambers of Xeric", type: "Mechanical" },
  { caTaskId: 307, name: "Mutta-diet", tier: "Elite", monster: "Chambers of Xeric", type: "Mechanical" },
  { caTaskId: 308, name: "Redemption Enthusiast", tier: "Elite", monster: "Chambers of Xeric", type: "Mechanical" },
  { caTaskId: 309, name: "Stop Drop and Roll", tier: "Master", monster: "Chambers of Xeric", type: "Mechanical" },
  { caTaskId: 310, name: "Anvil No More", tier: "Master", monster: "Chambers of Xeric", type: "Mechanical" },
  { caTaskId: 311, name: "Dancing with Statues", tier: "Elite", monster: "Chambers of Xeric", type: "Perfection" },
  { caTaskId: 312, name: "Undying Raid Team", tier: "Elite", monster: "Chambers of Xeric", type: "Perfection" },
  { caTaskId: 313, name: "Undying Raider", tier: "Master", monster: "Chambers of Xeric", type: "Perfection" },
  { caTaskId: 314, name: "Shayzien Specialist", tier: "Elite", monster: "Chambers of Xeric", type: "Perfection" },
  { caTaskId: 315, name: "Playing with Lasers", tier: "Master", monster: "Chambers of Xeric", type: "Perfection" },
  { caTaskId: 316, name: "Cryo No More", tier: "Elite", monster: "Chambers of Xeric", type: "Perfection" },
  { caTaskId: 317, name: "Perfect Olm (Solo)", tier: "Master", monster: "Chambers of Xeric", type: "Perfection" },
  { caTaskId: 318, name: "Perfect Olm (Trio)", tier: "Master", monster: "Chambers of Xeric", type: "Perfection" },
  { caTaskId: 319, name: "Blind Spot", tier: "Master", monster: "Chambers of Xeric", type: "Perfection" },
  { caTaskId: 320, name: "Blizzard Dodger", tier: "Elite", monster: "Chambers of Xeric", type: "Restriction" },
  { caTaskId: 321, name: "Kill It with Fire", tier: "Elite", monster: "Chambers of Xeric", type: "Restriction" },
  { caTaskId: 322, name: "Chambers of Xeric (Solo) Speed-Chaser", tier: "Master", monster: "Chambers of Xeric", type: "Speed" },
  { caTaskId: 323, name: "Chambers of Xeric (Solo) Speed-Runner", tier: "Grandmaster", monster: "Chambers of Xeric", type: "Speed" },
  { caTaskId: 324, name: "Chambers of Xeric (5-Scale) Speed-Chaser", tier: "Master", monster: "Chambers of Xeric", type: "Speed" },
  { caTaskId: 325, name: "Chambers of Xeric (5-Scale) Speed-Runner", tier: "Grandmaster", monster: "Chambers of Xeric", type: "Speed" },
  { caTaskId: 326, name: "Chambers of Xeric (Trio) Speed-Chaser", tier: "Master", monster: "Chambers of Xeric", type: "Speed" },
  { caTaskId: 327, name: "Chambers of Xeric (Trio) Speed-Runner", tier: "Grandmaster", monster: "Chambers of Xeric", type: "Speed" },
  { caTaskId: 328, name: "Zalcano Veteran", tier: "Elite", monster: "Zalcano", type: "Kill Count" },
  { caTaskId: 329, name: "Perfect Zalcano", tier: "Elite", monster: "Zalcano", type: "Perfection" },
  { caTaskId: 330, name: "Team Player", tier: "Elite", monster: "Zalcano", type: "Mechanical" },
  { caTaskId: 331, name: "The Spurned Hero", tier: "Elite", monster: "Zalcano", type: "Mechanical" },
  { caTaskId: 332, name: "K'ril Tsutsaroth Adept", tier: "Hard", monster: "K'ril Tsutsaroth", type: "Kill Count" },
  { caTaskId: 333, name: "K'ril Tsutsaroth Veteran", tier: "Elite", monster: "K'ril Tsutsaroth", type: "Kill Count" },
  { caTaskId: 334, name: "Yarr No More", tier: "Hard", monster: "K'ril Tsutsaroth", type: "Mechanical" },
  { caTaskId: 335, name: "Demonic Showdown", tier: "Hard", monster: "K'ril Tsutsaroth", type: "Mechanical" },
  { caTaskId: 336, name: "The Bane of Demons", tier: "Elite", monster: "K'ril Tsutsaroth", type: "Mechanical" },
  { caTaskId: 337, name: "Demonic Defence", tier: "Elite", monster: "K'ril Tsutsaroth", type: "Perfection" },
  { caTaskId: 338, name: "Demon Whisperer", tier: "Grandmaster", monster: "K'ril Tsutsaroth", type: "Perfection" },
  { caTaskId: 339, name: "Demonbane Weaponry II", tier: "Hard", monster: "K'ril Tsutsaroth", type: "Restriction" },
  { caTaskId: 340, name: "Ash Collector", tier: "Grandmaster", monster: "K'ril Tsutsaroth", type: "Stamina" },
  { caTaskId: 341, name: "Half-Way There", tier: "Elite", monster: "TzKal-Zuk", type: "Kill Count" },
  { caTaskId: 342, name: "Inferno Grandmaster", tier: "Grandmaster", monster: "TzKal-Zuk", type: "Kill Count" },
  { caTaskId: 343, name: "The Floor Is Lava", tier: "Grandmaster", monster: "TzKal-Zuk", type: "Mechanical" },
  { caTaskId: 344, name: "Playing with Jads", tier: "Grandmaster", monster: "TzKal-Zuk", type: "Mechanical" },
  { caTaskId: 345, name: "No Luck Required", tier: "Grandmaster", monster: "TzKal-Zuk", type: "Perfection" },
  { caTaskId: 346, name: "Nibblers, Begone!", tier: "Master", monster: "TzKal-Zuk", type: "Perfection" },
  { caTaskId: 347, name: "Wasn't Even Close", tier: "Grandmaster", monster: "TzKal-Zuk", type: "Restriction" },
  { caTaskId: 348, name: "Budget Setup", tier: "Grandmaster", monster: "TzKal-Zuk", type: "Restriction" },
  { caTaskId: 349, name: "Nibbler Chaser", tier: "Grandmaster", monster: "TzKal-Zuk", type: "Restriction" },
  { caTaskId: 350, name: "Facing Jad Head-on II", tier: "Grandmaster", monster: "TzKal-Zuk", type: "Restriction" },
  { caTaskId: 351, name: "Jad? What Are You Doing Here?", tier: "Grandmaster", monster: "TzKal-Zuk", type: "Restriction" },
  { caTaskId: 352, name: "Inferno Speed-Runner", tier: "Grandmaster", monster: "TzKal-Zuk", type: "Speed" },
  { caTaskId: 353, name: "Tempoross Novice", tier: "Easy", monster: "Tempoross", type: "Kill Count" },
  { caTaskId: 354, name: "Tempoross Champion", tier: "Medium", monster: "Tempoross", type: "Kill Count" },
  { caTaskId: 355, name: "Dress Like You Mean It", tier: "Hard", monster: "Tempoross", type: "Restriction" },
  { caTaskId: 356, name: "Master of Buckets", tier: "Easy", monster: "Tempoross", type: "Mechanical" },
  { caTaskId: 357, name: "Calm Before the Storm", tier: "Easy", monster: "Tempoross", type: "Mechanical" },
  { caTaskId: 358, name: "Why Cook?", tier: "Hard", monster: "Tempoross", type: "Mechanical" },
  { caTaskId: 359, name: "The Lone Angler", tier: "Medium", monster: "Tempoross", type: "Perfection" },
  { caTaskId: 360, name: "Fire in the Hole!", tier: "Easy", monster: "Tempoross", type: "Mechanical" },
  { caTaskId: 361, name: "The II Jad Challenge", tier: "Elite", monster: "TzHaar-Ket-Rak's Challenges", type: "Kill Count" },
  { caTaskId: 362, name: "The IV Jad Challenge", tier: "Master", monster: "TzHaar-Ket-Rak's Challenges", type: "Kill Count" },
  { caTaskId: 363, name: "The VI Jad Challenge", tier: "Grandmaster", monster: "TzHaar-Ket-Rak's Challenges", type: "Kill Count" },
  { caTaskId: 364, name: "TzHaar-Ket-Rak's Speed-Trialist", tier: "Elite", monster: "TzHaar-Ket-Rak's Challenges", type: "Speed" },
  { caTaskId: 365, name: "TzHaar-Ket-Rak's Speed-Chaser", tier: "Master", monster: "TzHaar-Ket-Rak's Challenges", type: "Speed" },
  { caTaskId: 366, name: "TzHaar-Ket-Rak's Speed-Runner", tier: "Grandmaster", monster: "TzHaar-Ket-Rak's Challenges", type: "Speed" },
  { caTaskId: 367, name: "Facing Jad Head-on III", tier: "Elite", monster: "TzHaar-Ket-Rak's Challenges", type: "Restriction" },
  { caTaskId: 368, name: "Facing Jad Head-on IV", tier: "Master", monster: "TzHaar-Ket-Rak's Challenges", type: "Restriction" },
  { caTaskId: 369, name: "Supplies? Who Needs 'em?", tier: "Master", monster: "TzHaar-Ket-Rak's Challenges", type: "Perfection" },
  { caTaskId: 370, name: "It Wasn't a Fluke", tier: "Grandmaster", monster: "TzHaar-Ket-Rak's Challenges", type: "Perfection" },
  { caTaskId: 371, name: "Multi-Style Specialist", tier: "Master", monster: "TzHaar-Ket-Rak's Challenges", type: "Mechanical" },
  { caTaskId: 372, name: "Stop Right There!", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Mechanical" },
  { caTaskId: 373, name: "Personal Space", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Mechanical" },
  { caTaskId: 374, name: "Royal Affairs", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Mechanical" },
  { caTaskId: 375, name: "Harder Mode I", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Perfection" },
  { caTaskId: 376, name: "Harder Mode II", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Perfection" },
  { caTaskId: 377, name: "Nylo Sniper", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Mechanical" },
  { caTaskId: 378, name: "Team Work Makes the Dream Work", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Mechanical" },
  { caTaskId: 379, name: "Harder Mode III", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Restriction" },
  { caTaskId: 380, name: "Pack Like a Yak", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Restriction" },
  { caTaskId: 381, name: "Hard Mode? Completed It", tier: "Master", monster: "Theatre of Blood: Hard Mode", type: "Speed" },
  { caTaskId: 382, name: "Theatre: HM (Trio) Speed-Runner", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Speed" },
  { caTaskId: 383, name: "Theatre: HM (4-Scale) Speed-Runner", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Speed" },
  { caTaskId: 384, name: "Theatre: HM (5-Scale) Speed-Runner", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Speed" },
  { caTaskId: 385, name: "Theatre of Blood: HM Grandmaster", tier: "Grandmaster", monster: "Theatre of Blood: Hard Mode", type: "Kill Count" },
  { caTaskId: 386, name: "Anticoagulants", tier: "Elite", monster: "Theatre of Blood: Entry Mode", type: "Mechanical" },
  { caTaskId: 387, name: "Appropriate Tools", tier: "Elite", monster: "Theatre of Blood: Entry Mode", type: "Mechanical" },
  { caTaskId: 388, name: "They Won't Expect This", tier: "Elite", monster: "Theatre of Blood: Entry Mode", type: "Mechanical" },
  { caTaskId: 389, name: "Chally Time", tier: "Elite", monster: "Theatre of Blood: Entry Mode", type: "Mechanical" },
  { caTaskId: 390, name: "Nylocas, On the Rocks", tier: "Elite", monster: "Theatre of Blood: Entry Mode", type: "Mechanical" },
  { caTaskId: 391, name: "Just To Be Safe", tier: "Elite", monster: "Theatre of Blood: Entry Mode", type: "Mechanical" },
  { caTaskId: 392, name: "Don't Look at Me!", tier: "Elite", monster: "Theatre of Blood: Entry Mode", type: "Mechanical" },
  { caTaskId: 393, name: "No-Pillar", tier: "Elite", monster: "Theatre of Blood: Entry Mode", type: "Mechanical" },
  { caTaskId: 394, name: "Attack, Step, Wait", tier: "Elite", monster: "Theatre of Blood: Entry Mode", type: "Mechanical" },
  { caTaskId: 395, name: "Pass It On", tier: "Elite", monster: "Theatre of Blood: Entry Mode", type: "Mechanical" },
  { caTaskId: 396, name: "Theatre of Blood: SM Speed-Chaser", tier: "Master", monster: "Theatre of Blood: Entry Mode", type: "Speed" },
  { caTaskId: 397, name: "Theatre of Blood: SM Adept", tier: "Hard", monster: "Theatre of Blood: Entry Mode", type: "Kill Count" },
  { caTaskId: 398, name: "Into the Den of Giants", tier: "Easy", monster: "Giants", type: "Kill Count" },
  { caTaskId: 399, name: "Sit Back and Relax", tier: "Medium", monster: "None", type: "Mechanical" },
  { caTaskId: 400, name: "Phosani's Veteran", tier: "Elite", monster: "Phosani's Nightmare", type: "Kill Count" },
  { caTaskId: 401, name: "Phosani's Master", tier: "Master", monster: "Phosani's Nightmare", type: "Kill Count" },
  { caTaskId: 402, name: "Phosani's Grandmaster", tier: "Grandmaster", monster: "Phosani's Nightmare", type: "Kill Count" },
  { caTaskId: 403, name: "Perfect Phosani's Nightmare", tier: "Grandmaster", monster: "Phosani's Nightmare", type: "Perfection" },
  { caTaskId: 404, name: "Phosani's Speedchaser", tier: "Master", monster: "Phosani's Nightmare", type: "Speed" },
  { caTaskId: 405, name: "Phosani's Speedrunner", tier: "Grandmaster", monster: "Phosani's Nightmare", type: "Speed" },
  { caTaskId: 406, name: "Crush Hour", tier: "Master", monster: "Phosani's Nightmare", type: "Mechanical" },
  { caTaskId: 407, name: "I Would Simply React", tier: "Master", monster: "Phosani's Nightmare", type: "Mechanical" },
  { caTaskId: 408, name: "Dreamland Express", tier: "Master", monster: "Phosani's Nightmare", type: "Mechanical" },
  { caTaskId: 409, name: "Can't Wake Up", tier: "Grandmaster", monster: "Phosani's Nightmare", type: "Stamina" },
  { caTaskId: 410, name: "Nex Veteran", tier: "Elite", monster: "Nex", type: "Kill Count" },
  { caTaskId: 411, name: "Nex Master", tier: "Master", monster: "Nex", type: "Kill Count" },
  { caTaskId: 412, name: "Nex Survivors", tier: "Elite", monster: "Nex", type: "Restriction" },
  { caTaskId: 413, name: "A siphon will solve this", tier: "Master", monster: "Nex", type: "Mechanical" },
  { caTaskId: 414, name: "Contain this!", tier: "Master", monster: "Nex", type: "Mechanical" },
  { caTaskId: 415, name: "There is no escape!", tier: "Master", monster: "Nex", type: "Mechanical" },
  { caTaskId: 416, name: "Nex Trio", tier: "Master", monster: "Nex", type: "Restriction" },
  { caTaskId: 417, name: "Nex Duo", tier: "Grandmaster", monster: "Nex", type: "Restriction" },
  { caTaskId: 418, name: "I should see a doctor", tier: "Grandmaster", monster: "Nex", type: "Restriction" },
  { caTaskId: 419, name: "Perfect Nex", tier: "Grandmaster", monster: "Nex", type: "Perfection" },
  { caTaskId: 420, name: "Shadows Move...", tier: "Master", monster: "Nex", type: "Mechanical" },
  { caTaskId: 421, name: "Tombs Speed Runner", tier: "Master", monster: "Tombs of Amascut", type: "Speed" },
  { caTaskId: 422, name: "Tombs Speed Runner II", tier: "Grandmaster", monster: "Tombs of Amascut: Expert Mode", type: "Speed" },
  { caTaskId: 423, name: "Tombs Speed Runner III", tier: "Grandmaster", monster: "Tombs of Amascut: Expert Mode", type: "Speed" },
  { caTaskId: 424, name: "You are not prepared", tier: "Master", monster: "Tombs of Amascut", type: "Restriction" },
  { caTaskId: 425, name: "Helpful spirit who?", tier: "Elite", monster: "Tombs of Amascut", type: "Restriction" },
  { caTaskId: 426, name: "Resourceful Raider", tier: "Master", monster: "Tombs of Amascut: Expert Mode", type: "Restriction" },
  { caTaskId: 427, name: "But... Damage", tier: "Master", monster: "Tombs of Amascut: Expert Mode", type: "Restriction" },
  { caTaskId: 428, name: "Chompington", tier: "Master", monster: "Tombs of Amascut", type: "Mechanical" },
  { caTaskId: 429, name: "Fancy feet", tier: "Master", monster: "Tombs of Amascut: Expert Mode", type: "Restriction" },
  { caTaskId: 430, name: "Hardcore Raiders", tier: "Elite", monster: "Tombs of Amascut", type: "Perfection" },
  { caTaskId: 431, name: "Hardcore Tombs", tier: "Elite", monster: "Tombs of Amascut", type: "Perfection" },
  { caTaskId: 432, name: "Perfect Het", tier: "Elite", monster: "Tombs of Amascut", type: "Perfection" },
  { caTaskId: 433, name: "Perfect Akkha", tier: "Master", monster: "Tombs of Amascut", type: "Perfection" },
  { caTaskId: 434, name: "Perfection of Het", tier: "Grandmaster", monster: "Tombs of Amascut: Expert Mode", type: "Perfection" },
  { caTaskId: 435, name: "Perfect Apmeken", tier: "Elite", monster: "Tombs of Amascut", type: "Perfection" },
  { caTaskId: 436, name: "Perfect Ba-Ba", tier: "Master", monster: "Tombs of Amascut", type: "Perfection" },
  { caTaskId: 437, name: "Perfection of Apmeken", tier: "Grandmaster", monster: "Tombs of Amascut: Expert Mode", type: "Perfection" },
  { caTaskId: 438, name: "Perfect Crondis", tier: "Elite", monster: "Tombs of Amascut", type: "Perfection" },
  { caTaskId: 439, name: "Perfect Zebak", tier: "Master", monster: "Tombs of Amascut", type: "Perfection" },
  { caTaskId: 440, name: "Perfection of Crondis", tier: "Grandmaster", monster: "Tombs of Amascut: Expert Mode", type: "Perfection" },
  { caTaskId: 441, name: "Perfect Scabaras", tier: "Master", monster: "Tombs of Amascut", type: "Perfection" },
  { caTaskId: 442, name: "Perfect Kephri", tier: "Master", monster: "Tombs of Amascut", type: "Perfection" },
  { caTaskId: 443, name: "Perfection of Scabaras", tier: "Grandmaster", monster: "Tombs of Amascut: Expert Mode", type: "Perfection" },
  { caTaskId: 444, name: "Perfect Wardens", tier: "Master", monster: "Tombs of Amascut", type: "Perfection" },
  { caTaskId: 445, name: "Insanity", tier: "Grandmaster", monster: "Tombs of Amascut: Expert Mode", type: "Perfection" },
  { caTaskId: 446, name: "Amascut's Remnant", tier: "Grandmaster", monster: "Tombs of Amascut: Expert Mode", type: "Mechanical" },
  { caTaskId: 447, name: "Something of an expert myself", tier: "Master", monster: "Tombs of Amascut: Expert Mode", type: "Mechanical" },
  { caTaskId: 448, name: "Maybe I'm the boss.", tier: "Grandmaster", monster: "Tombs of Amascut: Expert Mode", type: "Mechanical" },
  { caTaskId: 449, name: "Dropped the ball", tier: "Elite", monster: "Tombs of Amascut", type: "Mechanical" },
  { caTaskId: 450, name: "Akkhan't Do it", tier: "Grandmaster", monster: "Tombs of Amascut: Expert Mode", type: "Mechanical" },
  { caTaskId: 451, name: "No skipping allowed", tier: "Elite", monster: "Tombs of Amascut", type: "Mechanical" },
  { caTaskId: 452, name: "I'm in a rush", tier: "Elite", monster: "Tombs of Amascut", type: "Mechanical" },
  { caTaskId: 453, name: "Ba-Bananza", tier: "Master", monster: "Tombs of Amascut: Expert Mode", type: "Mechanical" },
  { caTaskId: 454, name: "All Praise Zebak", tier: "Grandmaster", monster: "Tombs of Amascut: Expert Mode", type: "Mechanical" },
  { caTaskId: 455, name: "Rockin' around the croc", tier: "Master", monster: "Tombs of Amascut: Expert Mode", type: "Mechanical" },
  { caTaskId: 456, name: "Doesn't bug me", tier: "Master", monster: "Tombs of Amascut: Expert Mode", type: "Mechanical" },
  { caTaskId: 457, name: "All out of medics", tier: "Master", monster: "Tombs of Amascut: Expert Mode", type: "Mechanical" },
  { caTaskId: 458, name: "Down Do Specs", tier: "Elite", monster: "Tombs of Amascut", type: "Mechanical" },
  { caTaskId: 459, name: "Better get movin'", tier: "Master", monster: "Tombs of Amascut", type: "Mechanical" },
  { caTaskId: 460, name: "Warden't you believe it", tier: "Master", monster: "Tombs of Amascut: Expert Mode", type: "Mechanical" },
  { caTaskId: 461, name: "Novice Tomb Explorer", tier: "Hard", monster: "Tombs of Amascut: Entry Mode", type: "Kill Count" },
  { caTaskId: 462, name: "Novice Tomb Looter", tier: "Hard", monster: "Tombs of Amascut: Entry Mode", type: "Kill Count" },
  { caTaskId: 463, name: "Novice Tomb Raider", tier: "Elite", monster: "Tombs of Amascut: Entry Mode", type: "Kill Count" },
  { caTaskId: 464, name: "Movin' on up", tier: "Hard", monster: "Tombs of Amascut: Entry Mode", type: "Restriction" },
  { caTaskId: 465, name: "Confident Raider", tier: "Hard", monster: "Tombs of Amascut: Entry Mode", type: "Restriction" },
  { caTaskId: 466, name: "Tomb Looter", tier: "Master", monster: "Tombs of Amascut", type: "Kill Count" },
  { caTaskId: 467, name: "Tomb Raider", tier: "Master", monster: "Tombs of Amascut", type: "Kill Count" },
  { caTaskId: 468, name: "Tomb Explorer", tier: "Elite", monster: "Tombs of Amascut", type: "Kill Count" },
  { caTaskId: 469, name: "Expert Tomb Explorer", tier: "Elite", monster: "Tombs of Amascut: Expert Mode", type: "Kill Count" },
  { caTaskId: 470, name: "Expert Tomb Looter", tier: "Master", monster: "Tombs of Amascut: Expert Mode", type: "Kill Count" },
  { caTaskId: 471, name: "Expert Tomb Raider", tier: "Grandmaster", monster: "Tombs of Amascut: Expert Mode", type: "Kill Count" },
  { caTaskId: 472, name: "More than just a ranged weapon", tier: "Master", monster: "Phantom Muspah", type: "Restriction" },
  { caTaskId: 473, name: "Can't Escape", tier: "Elite", monster: "Phantom Muspah", type: "Restriction" },
  { caTaskId: 474, name: "Essence Farmer", tier: "Master", monster: "Phantom Muspah", type: "Stamina" },
  { caTaskId: 475, name: "Phantom Muspah Speed-Trialist", tier: "Elite", monster: "Phantom Muspah", type: "Speed" },
  { caTaskId: 476, name: "Phantom Muspah Speed-Chaser", tier: "Master", monster: "Phantom Muspah", type: "Speed" },
  { caTaskId: 477, name: "Phantom Muspah Speed-Runner", tier: "Grandmaster", monster: "Phantom Muspah", type: "Speed" },
  { caTaskId: 478, name: "Phantom Muspah Adept", tier: "Hard", monster: "Phantom Muspah", type: "Kill Count" },
  { caTaskId: 479, name: "Phantom Muspah Veteran", tier: "Elite", monster: "Phantom Muspah", type: "Kill Count" },
  { caTaskId: 480, name: "Phantom Muspah Master", tier: "Master", monster: "Phantom Muspah", type: "Kill Count" },
  { caTaskId: 481, name: "Space is Tight", tier: "Master", monster: "Phantom Muspah", type: "Mechanical" },
  { caTaskId: 482, name: "Versatile Drainer", tier: "Elite", monster: "Phantom Muspah", type: "Mechanical" },
  { caTaskId: 483, name: "Walk Straight Pray True", tier: "Master", monster: "Phantom Muspah", type: "Perfection" },
  { caTaskId: 484, name: "Phantom Muspah Manipulator", tier: "Grandmaster", monster: "Phantom Muspah", type: "Perfection" },
  { caTaskId: 485, name: "Vardorvis Speed-Trialist", tier: "Elite", monster: "Vardorvis", type: "Speed" },
  { caTaskId: 486, name: "Vardorvis Speed-Chaser", tier: "Master", monster: "Vardorvis", type: "Speed" },
  { caTaskId: 487, name: "Vardorvis Speed-Runner", tier: "Grandmaster", monster: "Vardorvis", type: "Speed" },
  { caTaskId: 488, name: "Vardorvis Adept", tier: "Elite", monster: "Vardorvis", type: "Kill Count" },
  { caTaskId: 489, name: "Vardorvis Master", tier: "Master", monster: "Vardorvis", type: "Kill Count" },
  { caTaskId: 490, name: "Vardorvis Sleeper", tier: "Grandmaster", monster: "Vardorvis", type: "Kill Count" },
  { caTaskId: 491, name: "Perfect Vardorvis", tier: "Master", monster: "Vardorvis", type: "Perfection" },
  { caTaskId: 492, name: "Axe Enthusiast", tier: "Grandmaster", monster: "Vardorvis", type: "Mechanical" },
  { caTaskId: 493, name: "Budget Cutter", tier: "Master", monster: "Vardorvis", type: "Restriction" },
  { caTaskId: 494, name: "Whisperer Speed-Trialist", tier: "Elite", monster: "Whisperer", type: "Speed" },
  { caTaskId: 495, name: "Whisperer Speed-Chaser", tier: "Master", monster: "Whisperer", type: "Speed" },
  { caTaskId: 496, name: "Whisperer Speed-Runner", tier: "Grandmaster", monster: "Whisperer", type: "Speed" },
  { caTaskId: 497, name: "Whisperer Adept", tier: "Elite", monster: "Whisperer", type: "Kill Count" },
  { caTaskId: 498, name: "Whisperer Master", tier: "Master", monster: "Whisperer", type: "Kill Count" },
  { caTaskId: 499, name: "Whispered", tier: "Grandmaster", monster: "Whisperer", type: "Kill Count" },
  { caTaskId: 500, name: "Perfect Whisperer", tier: "Master", monster: "Whisperer", type: "Perfection" },
  { caTaskId: 501, name: "Tentacular", tier: "Elite", monster: "Whisperer", type: "Restriction" },
  { caTaskId: 502, name: "Dark Memories", tier: "Grandmaster", monster: "Whisperer", type: "Restriction" },
  { caTaskId: 503, name: "Leviathan Speed-Trialist", tier: "Elite", monster: "Leviathan", type: "Speed" },
  { caTaskId: 504, name: "Leviathan Speed-Chaser", tier: "Master", monster: "Leviathan", type: "Speed" },
  { caTaskId: 505, name: "Leviathan Speed-Runner", tier: "Grandmaster", monster: "Leviathan", type: "Speed" },
  { caTaskId: 506, name: "Leviathan Adept", tier: "Elite", monster: "Leviathan", type: "Kill Count" },
  { caTaskId: 507, name: "Leviathan Master", tier: "Master", monster: "Leviathan", type: "Kill Count" },
  { caTaskId: 508, name: "Leviathan Sleeper", tier: "Grandmaster", monster: "Leviathan", type: "Kill Count" },
  { caTaskId: 509, name: "Perfect Leviathan", tier: "Master", monster: "Leviathan", type: "Perfection" },
  { caTaskId: 510, name: "Serpentine Solo", tier: "Master", monster: "Leviathan", type: "Mechanical" },
  { caTaskId: 511, name: "Unconventional", tier: "Grandmaster", monster: "Leviathan", type: "Restriction" },
  { caTaskId: 512, name: "Duke Sucellus Speed-Trialist", tier: "Elite", monster: "Duke Sucellus", type: "Speed" },
  { caTaskId: 513, name: "Duke Sucellus Speed-Chaser", tier: "Master", monster: "Duke Sucellus", type: "Speed" },
  { caTaskId: 514, name: "Duke Sucellus Speed-Runner", tier: "Grandmaster", monster: "Duke Sucellus", type: "Speed" },
  { caTaskId: 515, name: "Duke Sucellus Adept", tier: "Elite", monster: "Duke Sucellus", type: "Kill Count" },
  { caTaskId: 516, name: "Duke Sucellus Master", tier: "Master", monster: "Duke Sucellus", type: "Kill Count" },
  { caTaskId: 517, name: "Duke Sucellus Sleeper", tier: "Grandmaster", monster: "Duke Sucellus", type: "Kill Count" },
  { caTaskId: 518, name: "Perfect Duke Sucellus", tier: "Master", monster: "Duke Sucellus", type: "Perfection" },
  { caTaskId: 519, name: "Cold Feet", tier: "Master", monster: "Duke Sucellus", type: "Restriction" },
  { caTaskId: 520, name: "Mirror Image", tier: "Grandmaster", monster: "Duke Sucellus", type: "Restriction" },
  { caTaskId: 521, name: "Scurrius Novice", tier: "Easy", monster: "Scurrius", type: "Kill Count" },
  { caTaskId: 522, name: "Scurrius Champion", tier: "Medium", monster: "Scurrius", type: "Kill Count" },
  { caTaskId: 523, name: "Sit Rat", tier: "Easy", monster: "Scurrius", type: "Restriction" },
  { caTaskId: 524, name: "Perfect Scurrius", tier: "Medium", monster: "Scurrius", type: "Perfection" },
  { caTaskId: 525, name: "Efficient Pest Control", tier: "Medium", monster: "Scurrius", type: "Mechanical" },
  { caTaskId: 526, name: "The Clone Zone", tier: "Hard", monster: "Moons of Peril", type: "Mechanical" },
  { caTaskId: 527, name: "High Hitter", tier: "Elite", monster: "Moons of Peril", type: "Mechanical" },
  { caTaskId: 528, name: "Lunar Triplet", tier: "Medium", monster: "Moons of Peril", type: "Kill Count" },
  { caTaskId: 529, name: "Perilous Novice", tier: "Medium", monster: "Moons of Peril", type: "Kill Count" },
  { caTaskId: 530, name: "Perilous Champion", tier: "Hard", monster: "Moons of Peril", type: "Kill Count" },
  { caTaskId: 531, name: "Perilous Dancer", tier: "Hard", monster: "Moons of Peril", type: "Perfection" },
  { caTaskId: 532, name: "Fortified", tier: "Hard", monster: "Moons of Peril", type: "Restriction" },
  { caTaskId: 533, name: "Betrayal", tier: "Hard", monster: "Moons of Peril", type: "Restriction" },
  { caTaskId: 534, name: "Back to Our Roots", tier: "Medium", monster: "Moons of Peril", type: "Restriction" },
  { caTaskId: 535, name: "Moons of Peril Speed-Trialist", tier: "Medium", monster: "Moons of Peril", type: "Speed" },
  { caTaskId: 536, name: "Moons of Peril Speed-Chaser", tier: "Hard", monster: "Moons of Peril", type: "Speed" },
  { caTaskId: 537, name: "Fat of the Land", tier: "Hard", monster: "Moons of Peril", type: "Stamina" },
  { caTaskId: 538, name: "Sportsmanship", tier: "Master", monster: "Fortis Colosseum", type: "Kill Count" },
  { caTaskId: 539, name: "Colosseum Grand Champion", tier: "Grandmaster", monster: "Fortis Colosseum", type: "Kill Count" },
  { caTaskId: 540, name: "I Brought Mine Too", tier: "Master", monster: "Fortis Colosseum", type: "Restriction" },
  { caTaskId: 541, name: "Slow Dancing in the Sand", tier: "Grandmaster", monster: "Fortis Colosseum", type: "Restriction" },
  { caTaskId: 542, name: "Furball", tier: "Elite", monster: "Fortis Colosseum", type: "Perfection" },
  { caTaskId: 543, name: "Perfect Footwork", tier: "Grandmaster", monster: "Fortis Colosseum", type: "Perfection" },
  { caTaskId: 544, name: "Showboating", tier: "Master", monster: "Fortis Colosseum", type: "Mechanical" },
  { caTaskId: 545, name: "Denied", tier: "Elite", monster: "Fortis Colosseum", type: "Mechanical" },
  { caTaskId: 546, name: "One-off", tier: "Master", monster: "Fortis Colosseum", type: "Mechanical" },
  { caTaskId: 547, name: "Reinforcements", tier: "Grandmaster", monster: "Fortis Colosseum", type: "Mechanical" },
  { caTaskId: 548, name: "I was here first!", tier: "Elite", monster: "Fortis Colosseum", type: "Mechanical" },
  { caTaskId: 549, name: "Colosseum Speed-Chaser", tier: "Master", monster: "Fortis Colosseum", type: "Speed" },
  { caTaskId: 550, name: "Colosseum Speed-Runner", tier: "Grandmaster", monster: "Fortis Colosseum", type: "Speed" },
  { caTaskId: 551, name: "Unending Torment", tier: "Elite", monster: "Tormented Demon", type: "Kill Count" },
  { caTaskId: 552, name: "Through Fire and Flames", tier: "Elite", monster: "Tormented Demon", type: "Restriction" },
  { caTaskId: 553, name: "Two Times the Torment", tier: "Elite", monster: "Tormented Demon", type: "Restriction" },
  { caTaskId: 554, name: "Three Times the Thrashing", tier: "Master", monster: "Tormented Demon", type: "Restriction" },
  { caTaskId: 555, name: "Rapid Reload", tier: "Elite", monster: "Tormented Demon", type: "Mechanical" },
  { caTaskId: 556, name: "Araxxor Veteran", tier: "Elite", monster: "Araxxor", type: "Kill Count" },
  { caTaskId: 557, name: "Araxxor Master", tier: "Master", monster: "Araxxor", type: "Kill Count" },
  { caTaskId: 558, name: "Araxxor Speed-Trialist", tier: "Elite", monster: "Araxxor", type: "Speed" },
  { caTaskId: 559, name: "Araxxor Speed-Chaser", tier: "Master", monster: "Araxxor", type: "Speed" },
  { caTaskId: 560, name: "Araxxor Speed-Runner", tier: "Grandmaster", monster: "Araxxor", type: "Speed" },
  { caTaskId: 561, name: "Perfect Araxxor", tier: "Master", monster: "Araxxor", type: "Perfection" },
  { caTaskId: 562, name: "Perfect Araxxor 2", tier: "Grandmaster", monster: "Araxxor", type: "Perfection" },
  { caTaskId: 563, name: "Let it seep in", tier: "Master", monster: "Araxxor", type: "Restriction" },
  { caTaskId: 564, name: "Relaxxor", tier: "Elite", monster: "Araxxor", type: "Restriction" },
  { caTaskId: 565, name: "Swimming in Venom", tier: "Grandmaster", monster: "Araxxor", type: "Restriction" },
  { caTaskId: 566, name: "Araxyte Betrayal", tier: "Master", monster: "Araxxor", type: "Mechanical" },
  { caTaskId: 567, name: "Arachnid Lover", tier: "Master", monster: "Araxxor", type: "Stamina" },
  { caTaskId: 568, name: "Hueycoatl Champion", tier: "Medium", monster: "The Hueycoatl", type: "Kill Count" },
  { caTaskId: 569, name: "Hueycoatl Adept", tier: "Hard", monster: "The Hueycoatl", type: "Kill Count" },
  { caTaskId: 570, name: "Hueycoatl Veteran", tier: "Elite", monster: "The Hueycoatl", type: "Kill Count" },
  { caTaskId: 571, name: "Perfect Hueycoatl", tier: "Elite", monster: "The Hueycoatl", type: "Perfection" },
  { caTaskId: 572, name: "Pillar Lover", tier: "Hard", monster: "The Hueycoatl", type: "Mechanical" },
  { caTaskId: 573, name: "Is it a bird?", tier: "Master", monster: "The Hueycoatl", type: "Restriction" },
  { caTaskId: 574, name: "You're a wizard", tier: "Medium", monster: "The Hueycoatl", type: "Restriction" },
  { caTaskId: 575, name: "I'm your son", tier: "Hard", monster: "The Hueycoatl", type: "Restriction" },
  { caTaskId: 576, name: "Hueycoatl Speed-Trialist", tier: "Elite", monster: "The Hueycoatl", type: "Speed" },
  { caTaskId: 577, name: "Hueycoatl Speed-Chaser", tier: "Master", monster: "The Hueycoatl", type: "Speed" },
  { caTaskId: 578, name: "Hueycoatl Speed-Runner", tier: "Grandmaster", monster: "The Hueycoatl", type: "Speed" },
  { caTaskId: 579, name: "Amoxliatl Champion", tier: "Medium", monster: "Amoxliatl", type: "Kill Count" },
  { caTaskId: 580, name: "Amoxliatl Adept", tier: "Hard", monster: "Amoxliatl", type: "Kill Count" },
  { caTaskId: 581, name: "Amoxliatl Speed-Trialist", tier: "Hard", monster: "Amoxliatl", type: "Speed" },
  { caTaskId: 582, name: "Amoxliatl Speed-Chaser", tier: "Elite", monster: "Amoxliatl", type: "Speed" },
  { caTaskId: 583, name: "Nagua Negation", tier: "Hard", monster: "Amoxliatl", type: "Perfection" },
  { caTaskId: 584, name: "Temotli Triumph", tier: "Medium", monster: "Amoxliatl", type: "Restriction" },
  { caTaskId: 585, name: "Without Ralos' Light", tier: "Elite", monster: "Amoxliatl", type: "Restriction" },
  { caTaskId: 586, name: "Kemo Makti", tier: "Hard", monster: "Amoxliatl", type: "Stamina" },
  { caTaskId: 587, name: "Totally Shattered", tier: "Hard", monster: "Amoxliatl", type: "Mechanical" },
  { caTaskId: 588, name: "Perfect Royal Titans", tier: "Hard", monster: "Royal Titans", type: "Perfection" },
  { caTaskId: 589, name: "Royal Titan Champion", tier: "Medium", monster: "Royal Titans", type: "Kill Count" },
  { caTaskId: 590, name: "Royal Titan Adept", tier: "Medium", monster: "Royal Titans", type: "Kill Count" },
  { caTaskId: 591, name: "One by one", tier: "Easy", monster: "Royal Titans", type: "Restriction" },
  { caTaskId: 592, name: "Royal Titan Speed-Runner", tier: "Hard", monster: "Royal Titans", type: "Speed" },
  { caTaskId: 593, name: "Titan Killer", tier: "Hard", monster: "Royal Titans", type: "Stamina" },
  { caTaskId: 594, name: "Elemental Company", tier: "Easy", monster: "Royal Titans", type: "Restriction" },
  { caTaskId: 595, name: "I need room", tier: "Hard", monster: "Royal Titans", type: "Restriction" },
  { caTaskId: 596, name: "No time to pray", tier: "Elite", monster: "Royal Titans", type: "Restriction" },
  { caTaskId: 597, name: "Let them fight", tier: "Easy", monster: "Royal Titans", type: "Restriction" },
  { caTaskId: 598, name: "It takes too long", tier: "Medium", monster: "Royal Titans", type: "Mechanical" },
  { caTaskId: 599, name: "Yama Adept", tier: "Elite", monster: "Yama", type: "Kill Count" },
  { caTaskId: 600, name: "Yama Veteran", tier: "Master", monster: "Yama", type: "Kill Count" },
  { caTaskId: 601, name: "Yama Speed-Trialist", tier: "Elite", monster: "Yama", type: "Speed" },
  { caTaskId: 602, name: "Yama Speed-Chaser", tier: "Master", monster: "Yama", type: "Speed" },
  { caTaskId: 603, name: "Yama Speed-Runner", tier: "Grandmaster", monster: "Yama", type: "Speed" },
  { caTaskId: 604, name: "No toppings, no drinks, thanks", tier: "Master", monster: "Yama", type: "Restriction" },
  { caTaskId: 605, name: "Shadow dancer", tier: "Master", monster: "Yama", type: "Mechanical" },
  { caTaskId: 606, name: "Fire fighter", tier: "Master", monster: "Yama", type: "Mechanical" },
  { caTaskId: 607, name: "Back so soon?", tier: "Elite", monster: "Yama", type: "Mechanical" },
  { caTaskId: 608, name: "Contract Choreographer", tier: "Grandmaster", monster: "Yama", type: "Perfection" },
  { caTaskId: 609, name: "Contractually Unbound", tier: "Grandmaster", monster: "Yama", type: "Kill Count" },
  { caTaskId: 610, name: "Doom Adept", tier: "Elite", monster: "Doom of Mokhaiotl", type: "Kill Count" },
  { caTaskId: 611, name: "Doom Veteran", tier: "Master", monster: "Doom of Mokhaiotl", type: "Kill Count" },
  { caTaskId: 612, name: "It's Dark Down Here", tier: "Grandmaster", monster: "Doom of Mokhaiotl", type: "Stamina" },
  { caTaskId: 613, name: "Exposed Doom", tier: "Elite", monster: "Doom of Mokhaiotl", type: "Mechanical" },
  { caTaskId: 614, name: "Mokhaiotl Drift", tier: "Master", monster: "Doom of Mokhaiotl", type: "Mechanical" },
  { caTaskId: 615, name: "Grub Patrol", tier: "Master", monster: "Doom of Mokhaiotl", type: "Mechanical" },
  { caTaskId: 616, name: "Perfect Doom", tier: "Grandmaster", monster: "Doom of Mokhaiotl", type: "Perfection" },
  { caTaskId: 617, name: "The Praying Mantis", tier: "Grandmaster", monster: "Doom of Mokhaiotl", type: "Restriction" },
  { caTaskId: 618, name: "Duel of Mokhaiotl", tier: "Grandmaster", monster: "Doom of Mokhaiotl", type: "Restriction" },
  { caTaskId: 619, name: "Darkness Is Your Ally?", tier: "Grandmaster", monster: "Doom of Mokhaiotl", type: "Restriction" },
  { caTaskId: 620, name: "Mine's Better", tier: "Master", monster: "Doom of Mokhaiotl", type: "Restriction" },
  { caTaskId: 621, name: "Doom Crawler", tier: "Elite", monster: "Doom of Mokhaiotl", type: "Speed" },
  { caTaskId: 622, name: "Doom Chaser", tier: "Master", monster: "Doom of Mokhaiotl", type: "Speed" },
  { caTaskId: 623, name: "Doom Racer", tier: "Grandmaster", monster: "Doom of Mokhaiotl", type: "Speed" },
  { caTaskId: 624, name: "Mopping up", tier: "Grandmaster", monster: "Doom of Mokhaiotl", type: "Mechanical" },
  { caTaskId: 625, name: "Shellbane Adept", tier: "Easy", monster: "Shellbane gryphon", type: "Kill Count" },
  { caTaskId: 626, name: "Shellbane Veteran", tier: "Medium", monster: "Shellbane gryphon", type: "Kill Count" },
  { caTaskId: 627, name: "Perfect Shellbane", tier: "Medium", monster: "Shellbane gryphon", type: "Perfection" },
  { caTaskId: 628, name: "Shellbane Speedrunner", tier: "Medium", monster: "Shellbane gryphon", type: "Speed" },
  { caTaskId: 629, name: "Shellbane Survivor", tier: "Hard", monster: "Shellbane gryphon", type: "Stamina" },
  { caTaskId: 630, name: "Dry Cleaning", tier: "Easy", monster: "Shellbane gryphon", type: "Mechanical" },
  { caTaskId: 631, name: "Featherweight Fighter", tier: "Hard", monster: "Shellbane gryphon", type: "Restriction" },
  { caTaskId: 632, name: "Brutus Novice", tier: "Easy", monster: "Brutus", type: "Kill Count" },
  { caTaskId: 633, name: "Brutus Champion", tier: "Medium", monster: "Brutus", type: "Kill Count" },
  { caTaskId: 634, name: "Brutus Speed-Trialist", tier: "Elite", monster: "Brutus", type: "Speed" },
  { caTaskId: 635, name: "Beef vs Beef", tier: "Medium", monster: "Brutus", type: "Perfection" },
  { caTaskId: 636, name: "Smarter than a Cow", tier: "Hard", monster: "Brutus", type: "Mechanical" },
];

export const CA_COUNT = CAS.length;
