/**
 * Quest reference data — RuneLite `net.runelite.api.Quest` enum constants.
 * The recipient's QuestTracker does `Quest.valueOf(questName)`, so a QUEST
 * goal auto-tracks ONLY when `questName` is the exact CONSTANT name
 * (e.g. "DRAGON_SLAYER_I"), never the display name. Includes miniquests
 * (QuestState resolves them the same way).
 *
 * GENERATED — do not hand-edit. Regenerate with `npm run gen:quests` (runs the
 * enum from the local runelite-api jar; see scripts/gen-quests.mjs).
 * Source: runelite-api 1.12.32-SNAPSHOT (210 quests).
 */

export interface QuestRef {
  /** Quest enum constant — the value `questName` must carry on the wire. */
  enumName: string;
  /** RuneLite quest id (informational; not used for tracking). */
  questId: number;
  /** In-game display name. */
  displayName: string;
}

export const QUESTS: readonly QuestRef[] = [
  { enumName: "A_KINGDOM_DIVIDED", questId: 81, displayName: "A Kingdom Divided" },
  { enumName: "A_NIGHT_AT_THE_THEATRE", questId: 104, displayName: "A Night at the Theatre" },
  { enumName: "A_PORCINE_OF_INTEREST", questId: 110, displayName: "A Porcine of Interest" },
  { enumName: "A_SOULS_BANE", questId: 138, displayName: "A Soul's Bane" },
  { enumName: "A_TAIL_OF_TWO_CATS", questId: 142, displayName: "A Tail of Two Cats" },
  { enumName: "A_TASTE_OF_HOPE", questId: 144, displayName: "A Taste of Hope" },
  { enumName: "ALFRED_GRIMHANDS_BARCRAWL", questId: 4, displayName: "Alfred Grimhand's Barcrawl" },
  { enumName: "ANIMAL_MAGNETISM", questId: 0, displayName: "Animal Magnetism" },
  { enumName: "ANOTHER_SLICE_OF_HAM", questId: 1, displayName: "Another Slice of H.A.M." },
  { enumName: "AT_FIRST_LIGHT", questId: 3513, displayName: "At First Light" },
  { enumName: "BARBARIAN_TRAINING", questId: 3451, displayName: "Barbarian Training" },
  { enumName: "BEAR_YOUR_SOUL", questId: 5, displayName: "Bear Your Soul" },
  { enumName: "BELOW_ICE_MOUNTAIN", questId: 6, displayName: "Below Ice Mountain" },
  { enumName: "BENEATH_CURSED_SANDS", questId: 168, displayName: "Beneath Cursed Sands" },
  { enumName: "BETWEEN_A_ROCK", questId: 7, displayName: "Between a Rock..." },
  { enumName: "BIG_CHOMPY_BIRD_HUNTING", questId: 8, displayName: "Big Chompy Bird Hunting" },
  { enumName: "BIOHAZARD", questId: 9, displayName: "Biohazard" },
  { enumName: "BLACK_KNIGHTS_FORTRESS", questId: 10, displayName: "Black Knights' Fortress" },
  { enumName: "BONE_VOYAGE", questId: 11, displayName: "Bone Voyage" },
  { enumName: "CABIN_FEVER", questId: 12, displayName: "Cabin Fever" },
  { enumName: "CHILDREN_OF_THE_SUN", questId: 3450, displayName: "Children of the Sun" },
  { enumName: "CLIENT_OF_KOUREND", questId: 13, displayName: "Client of Kourend" },
  { enumName: "CLOCK_TOWER", questId: 14, displayName: "Clock Tower" },
  { enumName: "COLD_WAR", questId: 15, displayName: "Cold War" },
  { enumName: "CONTACT", questId: 16, displayName: "Contact!" },
  { enumName: "COOKS_ASSISTANT", questId: 17, displayName: "Cook's Assistant" },
  { enumName: "CREATURE_OF_FENKENSTRAIN", questId: 19, displayName: "Creature of Fenkenstrain" },
  { enumName: "CURRENT_AFFAIRS", questId: 7105, displayName: "Current Affairs" },
  { enumName: "CURSE_OF_THE_EMPTY_LORD", questId: 20, displayName: "Curse of the Empty Lord" },
  { enumName: "DADDYS_HOME", questId: 21, displayName: "Daddy's Home" },
  { enumName: "DARKNESS_OF_HALLOWVALE", questId: 22, displayName: "Darkness of Hallowvale" },
  { enumName: "DEATH_ON_THE_ISLE", questId: 3711, displayName: "Death on the Isle" },
  { enumName: "DEATH_PLATEAU", questId: 23, displayName: "Death Plateau" },
  { enumName: "DEATH_TO_THE_DORGESHUUN", questId: 24, displayName: "Death to the Dorgeshuun" },
  { enumName: "DEFENDER_OF_VARROCK", questId: 3466, displayName: "Defender of Varrock" },
  { enumName: "DEMON_SLAYER", questId: 25, displayName: "Demon Slayer" },
  { enumName: "DESERT_TREASURE_I", questId: 27, displayName: "Desert Treasure I" },
  { enumName: "DESERT_TREASURE_II__THE_FALLEN_EMPIRE", questId: 2343, displayName: "Desert Treasure II - The Fallen Empire" },
  { enumName: "DEVIOUS_MINDS", questId: 28, displayName: "Devious Minds" },
  { enumName: "DORICS_QUEST", questId: 30, displayName: "Doric's Quest" },
  { enumName: "DRAGON_SLAYER_I", questId: 31, displayName: "Dragon Slayer I" },
  { enumName: "DRAGON_SLAYER_II", questId: 32, displayName: "Dragon Slayer II" },
  { enumName: "DREAM_MENTOR", questId: 33, displayName: "Dream Mentor" },
  { enumName: "DRUIDIC_RITUAL", questId: 34, displayName: "Druidic Ritual" },
  { enumName: "DWARF_CANNON", questId: 35, displayName: "Dwarf Cannon" },
  { enumName: "EADGARS_RUSE", questId: 36, displayName: "Eadgar's Ruse" },
  { enumName: "EAGLES_PEAK", questId: 37, displayName: "Eagles' Peak" },
  { enumName: "ELEMENTAL_WORKSHOP_I", questId: 38, displayName: "Elemental Workshop I" },
  { enumName: "ELEMENTAL_WORKSHOP_II", questId: 39, displayName: "Elemental Workshop II" },
  { enumName: "ENAKHRAS_LAMENT", questId: 40, displayName: "Enakhra's Lament" },
  { enumName: "ENLIGHTENED_JOURNEY", questId: 42, displayName: "Enlightened Journey" },
  { enumName: "ENTER_THE_ABYSS", questId: 43, displayName: "Enter the Abyss" },
  { enumName: "ERNEST_THE_CHICKEN", questId: 44, displayName: "Ernest the Chicken" },
  { enumName: "ETHICALLY_ACQUIRED_ANTIQUITIES", questId: 3713, displayName: "Ethically Acquired Antiquities" },
  { enumName: "FAIRYTALE_I__GROWING_PAINS", questId: 46, displayName: "Fairytale I - Growing Pains" },
  { enumName: "FAIRYTALE_II__CURE_A_QUEEN", questId: 47, displayName: "Fairytale II - Cure a Queen" },
  { enumName: "FAMILY_CREST", questId: 48, displayName: "Family Crest" },
  { enumName: "FAMILY_PEST", questId: 49, displayName: "Family Pest" },
  { enumName: "FIGHT_ARENA", questId: 51, displayName: "Fight Arena" },
  { enumName: "FISHING_CONTEST", questId: 52, displayName: "Fishing Contest" },
  { enumName: "FORGETTABLE_TALE", questId: 53, displayName: "Forgettable Tale..." },
  { enumName: "GARDEN_OF_TRANQUILLITY", questId: 58, displayName: "Garden of Tranquillity" },
  { enumName: "GERTRUDES_CAT", questId: 60, displayName: "Gertrude's Cat" },
  { enumName: "GETTING_AHEAD", questId: 61, displayName: "Getting Ahead" },
  { enumName: "GHOSTS_AHOY", questId: 62, displayName: "Ghosts Ahoy" },
  { enumName: "GOBLIN_DIPLOMACY", questId: 64, displayName: "Goblin Diplomacy" },
  { enumName: "GRIM_TALES", questId: 68, displayName: "Grim Tales" },
  { enumName: "HAUNTED_MINE", questId: 70, displayName: "Haunted Mine" },
  { enumName: "HAZEEL_CULT", questId: 71, displayName: "Hazeel Cult" },
  { enumName: "HEROES_QUEST", questId: 72, displayName: "Heroes' Quest" },
  { enumName: "HIS_FAITHFUL_SERVANTS", questId: 3250, displayName: "His Faithful Servants" },
  { enumName: "HOLY_GRAIL", questId: 73, displayName: "Holy Grail" },
  { enumName: "HOPESPEARS_WILL", questId: 166, displayName: "Hopespear's Will" },
  { enumName: "HORROR_FROM_THE_DEEP", questId: 74, displayName: "Horror from the Deep" },
  { enumName: "ICTHLARINS_LITTLE_HELPER", questId: 75, displayName: "Icthlarin's Little Helper" },
  { enumName: "IMP_CATCHER", questId: 76, displayName: "Imp Catcher" },
  { enumName: "IN_AID_OF_THE_MYREQUE", questId: 77, displayName: "In Aid of the Myreque" },
  { enumName: "IN_SEARCH_OF_KNOWLEDGE", questId: 78, displayName: "In Search of Knowledge" },
  { enumName: "IN_SEARCH_OF_THE_MYREQUE", questId: 79, displayName: "In Search of the Myreque" },
  { enumName: "INTO_THE_TOMBS", questId: 2306, displayName: "Into the Tombs" },
  { enumName: "JUNGLE_POTION", questId: 80, displayName: "Jungle Potion" },
  { enumName: "KINGS_RANSOM", questId: 82, displayName: "King's Ransom" },
  { enumName: "LAIR_OF_TARN_RAZORLOR", questId: 84, displayName: "Lair of Tarn Razorlor" },
  { enumName: "LAND_OF_THE_GOBLINS", questId: 165, displayName: "Land of the Goblins" },
  { enumName: "LEARNING_THE_ROPES", questId: 9643, displayName: "Learning the Ropes" },
  { enumName: "LEGENDS_QUEST", questId: 85, displayName: "Legends' Quest" },
  { enumName: "LOST_CITY", questId: 86, displayName: "Lost City" },
  { enumName: "LUNAR_DIPLOMACY", questId: 88, displayName: "Lunar Diplomacy" },
  { enumName: "MAGE_ARENA_I", questId: 89, displayName: "Mage Arena I" },
  { enumName: "MAGE_ARENA_II", questId: 90, displayName: "Mage Arena II" },
  { enumName: "MAKING_FRIENDS_WITH_MY_ARM", questId: 91, displayName: "Making Friends with My Arm" },
  { enumName: "MAKING_HISTORY", questId: 92, displayName: "Making History" },
  { enumName: "MEAT_AND_GREET", questId: 3712, displayName: "Meat and Greet" },
  { enumName: "MERLINS_CRYSTAL", questId: 93, displayName: "Merlin's Crystal" },
  { enumName: "MISTHALIN_MYSTERY", questId: 94, displayName: "Misthalin Mystery" },
  { enumName: "MONKEY_MADNESS_I", questId: 95, displayName: "Monkey Madness I" },
  { enumName: "MONKEY_MADNESS_II", questId: 96, displayName: "Monkey Madness II" },
  { enumName: "MONKS_FRIEND", questId: 97, displayName: "Monk's Friend" },
  { enumName: "MOUNTAIN_DAUGHTER", questId: 98, displayName: "Mountain Daughter" },
  { enumName: "MOURNINGS_END_PART_I", questId: 99, displayName: "Mourning's End Part I" },
  { enumName: "MOURNINGS_END_PART_II", questId: 100, displayName: "Mourning's End Part II" },
  { enumName: "MURDER_MYSTERY", questId: 101, displayName: "Murder Mystery" },
  { enumName: "MY_ARMS_BIG_ADVENTURE", questId: 102, displayName: "My Arm's Big Adventure" },
  { enumName: "NATURE_SPIRIT", questId: 103, displayName: "Nature Spirit" },
  { enumName: "OBSERVATORY_QUEST", questId: 105, displayName: "Observatory Quest" },
  { enumName: "OLAFS_QUEST", questId: 106, displayName: "Olaf's Quest" },
  { enumName: "ONE_SMALL_FAVOUR", questId: 107, displayName: "One Small Favour" },
  { enumName: "PANDEMONIUM", questId: 7103, displayName: "Pandemonium" },
  { enumName: "PERILOUS_MOONS", questId: 3514, displayName: "Perilous Moons" },
  { enumName: "PIRATES_TREASURE", questId: 108, displayName: "Pirate's Treasure" },
  { enumName: "PLAGUE_CITY", questId: 109, displayName: "Plague City" },
  { enumName: "PRIEST_IN_PERIL", questId: 111, displayName: "Priest in Peril" },
  { enumName: "PRINCE_ALI_RESCUE", questId: 112, displayName: "Prince Ali Rescue" },
  { enumName: "PRYING_TIMES", questId: 7104, displayName: "Prying Times" },
  { enumName: "RAG_AND_BONE_MAN_I", questId: 114, displayName: "Rag and Bone Man I" },
  { enumName: "RAG_AND_BONE_MAN_II", questId: 115, displayName: "Rag and Bone Man II" },
  { enumName: "RATCATCHERS", questId: 116, displayName: "Ratcatchers" },
  { enumName: "RECIPE_FOR_DISASTER", questId: 117, displayName: "Recipe for Disaster" },
  { enumName: "RECIPE_FOR_DISASTER__ANOTHER_COOKS_QUEST", questId: 2307, displayName: "Recipe for Disaster - Another Cook's Quest" },
  { enumName: "RECIPE_FOR_DISASTER__CULINAROMANCER", questId: 2316, displayName: "Recipe for Disaster - Culinaromancer" },
  { enumName: "RECIPE_FOR_DISASTER__EVIL_DAVE", questId: 2312, displayName: "Recipe for Disaster - Evil Dave" },
  { enumName: "RECIPE_FOR_DISASTER__KING_AWOWOGEI", questId: 2315, displayName: "Recipe for Disaster - King Awowogei" },
  { enumName: "RECIPE_FOR_DISASTER__LUMBRIDGE_GUIDE", questId: 2311, displayName: "Recipe for Disaster - Lumbridge Guide" },
  { enumName: "RECIPE_FOR_DISASTER__MOUNTAIN_DWARF", questId: 2308, displayName: "Recipe for Disaster - Mountain Dwarf" },
  { enumName: "RECIPE_FOR_DISASTER__PIRATE_PETE", questId: 2310, displayName: "Recipe for Disaster - Pirate Pete" },
  { enumName: "RECIPE_FOR_DISASTER__SIR_AMIK_VARZE", questId: 2314, displayName: "Recipe for Disaster - Sir Amik Varze" },
  { enumName: "RECIPE_FOR_DISASTER__SKRACH_UGLOGWEE", questId: 2313, displayName: "Recipe for Disaster - Skrach Uglogwee" },
  { enumName: "RECIPE_FOR_DISASTER__WARTFACE__BENTNOZE", questId: 2309, displayName: "Recipe for Disaster - Wartface & Bentnoze" },
  { enumName: "RECRUITMENT_DRIVE", questId: 118, displayName: "Recruitment Drive" },
  { enumName: "REGICIDE", questId: 119, displayName: "Regicide" },
  { enumName: "ROMEO__JULIET", questId: 121, displayName: "Romeo & Juliet" },
  { enumName: "ROVING_ELVES", questId: 122, displayName: "Roving Elves" },
  { enumName: "ROYAL_TROUBLE", questId: 123, displayName: "Royal Trouble" },
  { enumName: "RUM_DEAL", questId: 124, displayName: "Rum Deal" },
  { enumName: "RUNE_MYSTERIES", questId: 125, displayName: "Rune Mysteries" },
  { enumName: "SCORPION_CATCHER", questId: 126, displayName: "Scorpion Catcher" },
  { enumName: "SCRAMBLED", questId: 5191, displayName: "Scrambled!" },
  { enumName: "SEA_SLUG", questId: 127, displayName: "Sea Slug" },
  { enumName: "SECRETS_OF_THE_NORTH", questId: 2338, displayName: "Secrets of the North" },
  { enumName: "SHADES_OF_MORTTON", questId: 128, displayName: "Shades of Mort'ton" },
  { enumName: "SHADOW_OF_THE_STORM", questId: 129, displayName: "Shadow of the Storm" },
  { enumName: "SHADOWS_OF_CUSTODIA", questId: 5190, displayName: "Shadows of Custodia" },
  { enumName: "SHEEP_HERDER", questId: 130, displayName: "Sheep Herder" },
  { enumName: "SHEEP_SHEARER", questId: 131, displayName: "Sheep Shearer" },
  { enumName: "SHIELD_OF_ARRAV", questId: 132, displayName: "Shield of Arrav" },
  { enumName: "SHILO_VILLAGE", questId: 133, displayName: "Shilo Village" },
  { enumName: "SINS_OF_THE_FATHER", questId: 134, displayName: "Sins of the Father" },
  { enumName: "SKIPPY_AND_THE_MOGRES", questId: 135, displayName: "Skippy and the Mogres" },
  { enumName: "SLEEPING_GIANTS", questId: 169, displayName: "Sleeping Giants" },
  { enumName: "SONG_OF_THE_ELVES", questId: 137, displayName: "Song of the Elves" },
  { enumName: "SPIRITS_OF_THE_ELID", questId: 139, displayName: "Spirits of the Elid" },
  { enumName: "SWAN_SONG", questId: 140, displayName: "Swan Song" },
  { enumName: "TAI_BWO_WANNAI_TRIO", questId: 141, displayName: "Tai Bwo Wannai Trio" },
  { enumName: "TALE_OF_THE_RIGHTEOUS", questId: 143, displayName: "Tale of the Righteous" },
  { enumName: "TEARS_OF_GUTHIX", questId: 145, displayName: "Tears of Guthix" },
  { enumName: "TEMPLE_OF_IKOV", questId: 146, displayName: "Temple of Ikov" },
  { enumName: "TEMPLE_OF_THE_EYE", questId: 167, displayName: "Temple of the Eye" },
  { enumName: "THE_ASCENT_OF_ARCEUUS", questId: 3, displayName: "The Ascent of Arceuus" },
  { enumName: "THE_BLOOD_MOON_RISES", questId: 16414, displayName: "The Blood Moon Rises" },
  { enumName: "THE_CORSAIR_CURSE", questId: 18, displayName: "The Corsair Curse" },
  { enumName: "THE_CURSE_OF_ARRAV", questId: 3937, displayName: "The Curse of Arrav" },
  { enumName: "THE_DEPTHS_OF_DESPAIR", questId: 26, displayName: "The Depths of Despair" },
  { enumName: "THE_DIG_SITE", questId: 29, displayName: "The Dig Site" },
  { enumName: "THE_ENCHANTED_KEY", questId: 41, displayName: "The Enchanted Key" },
  { enumName: "THE_EYES_OF_GLOUPHRIE", questId: 45, displayName: "The Eyes of Glouphrie" },
  { enumName: "THE_FEUD", questId: 50, displayName: "The Feud" },
  { enumName: "THE_FINAL_DAWN", questId: 5189, displayName: "The Final Dawn" },
  { enumName: "THE_FORSAKEN_TOWER", questId: 54, displayName: "The Forsaken Tower" },
  { enumName: "THE_FREMENNIK_EXILES", questId: 55, displayName: "The Fremennik Exiles" },
  { enumName: "THE_FREMENNIK_ISLES", questId: 56, displayName: "The Fremennik Isles" },
  { enumName: "THE_FREMENNIK_TRIALS", questId: 57, displayName: "The Fremennik Trials" },
  { enumName: "THE_FROZEN_DOOR", questId: 164, displayName: "The Frozen Door" },
  { enumName: "THE_GARDEN_OF_DEATH", questId: 180, displayName: "The Garden of Death" },
  { enumName: "THE_GENERALS_SHADOW", questId: 59, displayName: "The General's Shadow" },
  { enumName: "THE_GIANT_DWARF", questId: 63, displayName: "The Giant Dwarf" },
  { enumName: "THE_GOLEM", questId: 65, displayName: "The Golem" },
  { enumName: "THE_GRAND_TREE", questId: 66, displayName: "The Grand Tree" },
  { enumName: "THE_GREAT_BRAIN_ROBBERY", questId: 67, displayName: "The Great Brain Robbery" },
  { enumName: "THE_HAND_IN_THE_SAND", questId: 69, displayName: "The Hand in the Sand" },
  { enumName: "THE_HEART_OF_DARKNESS", questId: 3710, displayName: "The Heart of Darkness" },
  { enumName: "THE_IDES_OF_MILK", questId: 9645, displayName: "The Ides of Milk" },
  { enumName: "THE_KNIGHTS_SWORD", questId: 83, displayName: "The Knight's Sword" },
  { enumName: "THE_LOST_TRIBE", questId: 87, displayName: "The Lost Tribe" },
  { enumName: "THE_PATH_OF_GLOUPHRIE", questId: 3425, displayName: "The Path of Glouphrie" },
  { enumName: "THE_QUEEN_OF_THIEVES", questId: 113, displayName: "The Queen of Thieves" },
  { enumName: "THE_RED_REEF", questId: 7107, displayName: "The Red Reef" },
  { enumName: "THE_RESTLESS_GHOST", questId: 120, displayName: "The Restless Ghost" },
  { enumName: "THE_RIBBITING_TALE_OF_A_LILY_PAD_LABOUR_DISPUTE", questId: 3515, displayName: "The Ribbiting Tale of a Lily Pad Labour Dispute" },
  { enumName: "THE_SLUG_MENACE", questId: 136, displayName: "The Slug Menace" },
  { enumName: "THE_TOURIST_TRAP", questId: 148, displayName: "The Tourist Trap" },
  { enumName: "THRONE_OF_MISCELLANIA", questId: 147, displayName: "Throne of Miscellania" },
  { enumName: "TOWER_OF_LIFE", questId: 149, displayName: "Tower of Life" },
  { enumName: "TREE_GNOME_VILLAGE", questId: 150, displayName: "Tree Gnome Village" },
  { enumName: "TRIBAL_TOTEM", questId: 151, displayName: "Tribal Totem" },
  { enumName: "TROLL_ROMANCE", questId: 152, displayName: "Troll Romance" },
  { enumName: "TROLL_STRONGHOLD", questId: 153, displayName: "Troll Stronghold" },
  { enumName: "TROUBLED_TORTUGANS", questId: 7106, displayName: "Troubled Tortugans" },
  { enumName: "TWILIGHTS_PROMISE", questId: 3512, displayName: "Twilight's Promise" },
  { enumName: "UNDERGROUND_PASS", questId: 154, displayName: "Underground Pass" },
  { enumName: "VALE_TOTEMS", questId: 5194, displayName: "Vale Totems" },
  { enumName: "VAMPYRE_SLAYER", questId: 155, displayName: "Vampyre Slayer" },
  { enumName: "WANTED", questId: 156, displayName: "Wanted!" },
  { enumName: "WATCHTOWER", questId: 157, displayName: "Watchtower" },
  { enumName: "WATERFALL_QUEST", questId: 158, displayName: "Waterfall Quest" },
  { enumName: "WHAT_LIES_BELOW", questId: 159, displayName: "What Lies Below" },
  { enumName: "WHILE_GUTHIX_SLEEPS", questId: 3467, displayName: "While Guthix Sleeps" },
  { enumName: "WITCHS_HOUSE", questId: 160, displayName: "Witch's House" },
  { enumName: "WITCHS_POTION", questId: 161, displayName: "Witch's Potion" },
  { enumName: "X_MARKS_THE_SPOT", questId: 162, displayName: "X Marks the Spot" },
  { enumName: "ZOGRE_FLESH_EATERS", questId: 163, displayName: "Zogre Flesh Eaters" },
];

export const QUEST_COUNT = QUESTS.length;
